{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowDeviceMotionDetection","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"abstract":[{"type":"text","text":"Allow the SDK to collect device motion data. This feature is disabled when "},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowTouchDetection","type":"reference"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":". The SDK is creating an instance of "},{"code":"CMMotionManager","type":"codeVoice"},{"type":"text","text":" to monitor device’s motion. However, it’s not recommended to have more than one instance in the app. By setting this property to "},{"type":"codeVoice","code":"false"},{"text":", the SDK won’t create an instance of ","type":"text"},{"code":"CMMotionManager","type":"codeVoice"},{"type":"text","text":". Default is "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowDeviceMotionDetection"},"variants":[{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/allowdevicemotiondetection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/allowdevicemotiondetection"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"allowDeviceMotionDetection","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowDeviceMotionDetection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"allowDeviceMotionDetection"}],"externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(py)allowDeviceMotionDetection","symbolKind":"property","modules":[{"name":"PerimeterX_SDK"}],"role":"symbol"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk","abstract":[],"title":"PerimeterX_SDK"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/allowTouchDetection":{"abstract":[{"type":"text","text":"Allow the SDK to intercept touches on the screen. Default is "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowTouchDetection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowTouchDetection","navigatorTitle":[{"text":"allowTouchDetection","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/allowtouchdetection","type":"topic","title":"allowTouchDetection","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","type":"topic","role":"symbol","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PXPolicy"}],"title":"PXPolicy","navigatorTitle":[{"kind":"identifier","text":"PXPolicy"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/allowDeviceMotionDetection":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowDeviceMotionDetection","type":"topic","role":"symbol","abstract":[{"text":"Allow the SDK to collect device motion data. This feature is disabled when ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowTouchDetection","isActive":true},{"type":"text","text":" is "},{"type":"codeVoice","code":"false"},{"text":". The SDK is creating an instance of ","type":"text"},{"type":"codeVoice","code":"CMMotionManager"},{"text":" to monitor device’s motion. However, it’s not recommended to have more than one instance in the app. By setting this property to ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":", the SDK won’t create an instance of "},{"type":"codeVoice","code":"CMMotionManager"},{"text":". Default is ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/allowdevicemotiondetection","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowDeviceMotionDetection","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"allowDeviceMotionDetection","navigatorTitle":[{"text":"allowDeviceMotionDetection","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"allowDeviceMotionDetection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"allowDeviceMotionDetection","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"allowDeviceMotionDetection","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1allowTouchDetection\/title","op":"replace","value":"allowTouchDetection"},{"op":"replace","value":[{"kind":"identifier","text":"allowTouchDetection"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1allowTouchDetection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","value":"PXPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","value":[{"text":"PXPolicy","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1allowDeviceMotionDetection\/title","value":"allowDeviceMotionDetection","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1allowDeviceMotionDetection\/fragments","value":[{"text":"allowDeviceMotionDetection","kind":"identifier"}]}]}]}