{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URLSessionDelegate"},{"type":"text","text":" that should be used by the SDK. Default is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" (the SDK will be the delegate). The SDK implements "},{"type":"codeVoice","code":"willPerformHTTPRedirection"},{"type":"text","text":" and "},{"type":"codeVoice","code":"needNewBodyStream"},{"type":"text","text":" function in the "},{"type":"codeVoice","code":"URLSessionDelegate"},{"type":"text","text":". However, if your "},{"type":"codeVoice","code":"URLSessionDelegate"},{"type":"text","text":" implements other functions, like "},{"type":"codeVoice","code":"didReceiveChallenge"},{"type":"text","text":", then you should provide your own delegate."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptorurlsessiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptorurlsessiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorUrlSessionDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticInterceptorUrlSessionDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSURLSessionDelegate","text":"URLSessionDelegate"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"automaticInterceptorUrlSessionDelegate"}],"externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(cpy)automaticInterceptorUrlSessionDelegate","roleHeading":"Type Property","modules":[{"name":"PerimeterX_SDK"}],"role":"symbol","title":"automaticInterceptorUrlSessionDelegate"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticInterceptorUrlSessionDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionDelegate","preciseIdentifier":"c:objc(pl)NSURLSessionDelegate"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/automaticInterceptorUrlSessionDelegate":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"automaticInterceptorUrlSessionDelegate"}],"type":"topic","title":"automaticInterceptorUrlSessionDelegate","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticInterceptorUrlSessionDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionDelegate","preciseIdentifier":"c:objc(pl)NSURLSessionDelegate"},{"kind":"text","text":"?"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptorurlsessiondelegate","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URLSessionDelegate"},{"type":"text","text":" that should be used by the SDK. Default is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" (the SDK will be the delegate). The SDK implements "},{"type":"codeVoice","code":"willPerformHTTPRedirection"},{"type":"text","text":" and "},{"type":"codeVoice","code":"needNewBodyStream"},{"type":"text","text":" function in the "},{"type":"codeVoice","code":"URLSessionDelegate"},{"type":"text","text":". However, if your "},{"type":"codeVoice","code":"URLSessionDelegate"},{"type":"text","text":" implements other functions, like "},{"type":"codeVoice","code":"didReceiveChallenge"},{"type":"text","text":", then you should provide your own delegate."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorUrlSessionDelegate"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PXPolicy","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","navigatorTitle":[{"text":"PXPolicy","kind":"identifier"}],"kind":"symbol","type":"topic","title":"PXPolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","title":"PerimeterX_SDK","kind":"symbol","abstract":[],"url":"\/documentation\/perimeterx_sdk","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"automaticInterceptorUrlSessionDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"automaticInterceptorUrlSessionDelegate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<NSURLSessionDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)NSURLSessionDelegate"},{"text":" ","kind":"text"},{"text":"automaticInterceptorUrlSessionDelegate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorUrlSessionDelegate\/title","value":"automaticInterceptorUrlSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorUrlSessionDelegate\/fragments","value":[{"kind":"identifier","text":"automaticInterceptorUrlSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","value":"PXPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","value":[{"text":"PXPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/navigatorTitle","value":[{"text":"PXPolicy","kind":"identifier"}]}]}]}