{"sections":[],"metadata":{"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automaticInterceptorDelegateQueue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"OperationQueue","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Type Property","modules":[{"name":"PerimeterX_SDK"}],"externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(cpy)automaticInterceptorDelegateQueue","role":"symbol","navigatorTitle":[{"text":"automaticInterceptorDelegateQueue","kind":"identifier"}],"title":"automaticInterceptorDelegateQueue"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticInterceptorDelegateQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","kind":"typeIdentifier","text":"OperationQueue"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptordelegatequeue"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptordelegatequeue"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorDelegateQueue"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"OperationQueue"},{"text":" that should be used by the SDK.","type":"text"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/automaticInterceptorDelegateQueue":{"role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"OperationQueue"},{"text":" that should be used by the SDK.","type":"text"}],"title":"automaticInterceptorDelegateQueue","navigatorTitle":[{"text":"automaticInterceptorDelegateQueue","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorDelegateQueue","type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptordelegatequeue","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"automaticInterceptorDelegateQueue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"OperationQueue"},{"kind":"text","text":"?"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"title":"PXPolicy","url":"\/documentation\/perimeterx_sdk\/pxpolicy","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PXPolicy","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"PXPolicy","kind":"identifier"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"role":"collection","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","title":"PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"automaticInterceptorDelegateQueue"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"automaticInterceptorDelegateQueue"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"NSOperationQueue","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"automaticInterceptorDelegateQueue"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorDelegateQueue\/title","value":"automaticInterceptorDelegateQueue","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorDelegateQueue\/fragments","value":[{"text":"automaticInterceptorDelegateQueue","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","value":"PXPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","value":[{"text":"PXPolicy","kind":"identifier"}]}]}]}