{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automaticInterceptorUrlSessionConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"URLSessionConfiguration"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"abstract":[{"type":"text","text":"The "},{"code":"URLSessionConfiguration","type":"codeVoice"},{"text":" that should be used by the SDK. Default is ","type":"text"},{"code":"URLSessionConfiguration.default","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorUrlSessionConfiguration","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptorurlsessionconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptorurlsessionconfiguration"]}],"sections":[],"kind":"symbol","metadata":{"title":"automaticInterceptorUrlSessionConfiguration","roleHeading":"Type Property","modules":[{"name":"PerimeterX_SDK"}],"externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(cpy)automaticInterceptorUrlSessionConfiguration","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticInterceptorUrlSessionConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"automaticInterceptorUrlSessionConfiguration"}]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/automaticInterceptorUrlSessionConfiguration":{"kind":"symbol","title":"automaticInterceptorUrlSessionConfiguration","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptorurlsessionconfiguration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URLSessionConfiguration"},{"text":" that should be used by the SDK. Default is ","type":"text"},{"code":"URLSessionConfiguration.default","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automaticInterceptorUrlSessionConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"}],"navigatorTitle":[{"text":"automaticInterceptorUrlSessionConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorUrlSessionConfiguration","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"title":"PXPolicy","url":"\/documentation\/perimeterx_sdk\/pxpolicy","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PXPolicy","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"PXPolicy","kind":"identifier"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"url":"\/documentation\/perimeterx_sdk","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","abstract":[],"type":"topic","title":"PerimeterX_SDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"automaticInterceptorUrlSessionConfiguration","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"automaticInterceptorUrlSessionConfiguration","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"NSURLSessionConfiguration"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"automaticInterceptorUrlSessionConfiguration"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"automaticInterceptorUrlSessionConfiguration","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorUrlSessionConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorUrlSessionConfiguration\/fragments","value":[{"text":"automaticInterceptorUrlSessionConfiguration","kind":"identifier"}]},{"value":"PXPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PXPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments"}]}]}