{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"challengeType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType","preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyChallengeType","text":"PXPolicyChallengeType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/challengetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/challengetype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/challengeType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Challenge type. Default is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/webView"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"challengeType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PXPolicyChallengeType","preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyChallengeType"}],"title":"challengeType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(py)challengeType","modules":[{"name":"PerimeterX_SDK"}],"navigatorTitle":[{"kind":"identifier","text":"challengeType"}]},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyChallengeType/webView":{"role":"symbol","title":"PXPolicyChallengeType.webView","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"}],"abstract":[{"type":"text","text":"WebView challenge."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/webView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PXPolicyChallengeTypeWebView"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicychallengetype\/webview"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyChallengeType":{"role":"symbol","title":"PXPolicyChallengeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PXPolicyChallengeType"}],"abstract":[{"type":"text","text":"Challenge type."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PXPolicyChallengeType"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicychallengetype"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/challengeType":{"role":"symbol","title":"challengeType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"challengeType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PXPolicyChallengeType","preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyChallengeType"}],"abstract":[{"type":"text","text":"Challenge type. Default is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/webView"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/challengeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"challengeType"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/challengetype"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"role":"collection","title":"PerimeterX_SDK","abstract":[{"type":"image","identifier":"PerimeterX.png"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","kind":"symbol","type":"topic","url":"\/documentation\/perimeterx_sdk"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"role":"symbol","title":"PXPolicy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PXPolicy"}],"abstract":[{"type":"text","text":"The policy that defines the behaviour of the SDK."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PXPolicy"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"challengeType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"challengeType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType","preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyChallengeType","text":"PXPolicyChallengeType"},{"kind":"text","text":" "},{"kind":"identifier","text":"challengeType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyChallengeType~1webView\/title","value":"PXPolicyChallengeTypeWebView"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyChallengeType~1webView\/fragments","value":[{"kind":"identifier","text":"PXPolicyChallengeTypeWebView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyChallengeType\/title","value":"PXPolicyChallengeType"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyChallengeType\/fragments","value":[{"kind":"identifier","text":"PXPolicyChallengeType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1challengeType\/title","value":"challengeType"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1challengeType\/fragments","value":[{"kind":"identifier","text":"challengeType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","value":"PXPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","value":[{"kind":"identifier","text":"PXPolicy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}