{"variants":[{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/delayresponseuntilchallengesolvedorcancelled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/delayresponseuntilchallengesolvedorcancelled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/delayResponseUntilChallengeSolvedOrCancelled","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delayResponseUntilChallengeSolvedOrCancelled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"symbolKind":"property","externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(py)delayResponseUntilChallengeSolvedOrCancelled","title":"delayResponseUntilChallengeSolvedOrCancelled","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"PerimeterX_SDK"}],"navigatorTitle":[{"text":"delayResponseUntilChallengeSolvedOrCancelled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delayResponseUntilChallengeSolvedOrCancelled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Indication that responses for blocked requests should be delayed until the challenge was solved or cancelled by the user. This property is relevant only when "},{"type":"codeVoice","code":"requestsInterceptedAutomaticallyEnabled"},{"text":" is true.Notice that enabling this could mean that your request handler code will not be called at all (for example, when the user does not solve the challenge). Default is false.","type":"text"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","kind":"symbol","url":"\/documentation\/perimeterx_sdk","title":"PerimeterX_SDK","type":"topic","abstract":[{"type":"image","identifier":"PerimeterX.png"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/delayResponseUntilChallengeSolvedOrCancelled":{"abstract":[{"type":"text","text":"Indication that responses for blocked requests should be delayed until the challenge was solved or cancelled by the user. This property is relevant only when "},{"code":"requestsInterceptedAutomaticallyEnabled","type":"codeVoice"},{"type":"text","text":" is true.Notice that enabling this could mean that your request handler code will not be called at all (for example, when the user does not solve the challenge). Default is false."}],"title":"delayResponseUntilChallengeSolvedOrCancelled","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/delayResponseUntilChallengeSolvedOrCancelled","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/delayresponseuntilchallengesolvedorcancelled","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delayResponseUntilChallengeSolvedOrCancelled"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delayResponseUntilChallengeSolvedOrCancelled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The policy that defines the behaviour of the SDK."}],"type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicy","navigatorTitle":[{"text":"PXPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","title":"PXPolicy","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PXPolicy"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"delayResponseUntilChallengeSolvedOrCancelled","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"delayResponseUntilChallengeSolvedOrCancelled"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delayResponseUntilChallengeSolvedOrCancelled"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1delayResponseUntilChallengeSolvedOrCancelled\/title","value":"delayResponseUntilChallengeSolvedOrCancelled","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1delayResponseUntilChallengeSolvedOrCancelled\/fragments","op":"replace","value":[{"kind":"identifier","text":"delayResponseUntilChallengeSolvedOrCancelled"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","op":"replace","value":"PXPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","op":"replace","value":[{"kind":"identifier","text":"PXPolicy"}]}]}]}