{"abstract":[{"type":"text","text":"Set this property to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" to enable the "},{"code":"Doctor App","type":"codeVoice"},{"type":"text","text":" - a tool to verify the integration of the SDK in your app. Make sure to set this property to "},{"type":"codeVoice","code":"false"},{"type":"text","text":" before deploying you app to production. Default is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"doctorCheckEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/doctorcheckenabled"]},{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/doctorcheckenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/doctorCheckEnabled"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"sections":[],"metadata":{"title":"doctorCheckEnabled","modules":[{"name":"PerimeterX_SDK"}],"roleHeading":"Instance Property","externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(py)doctorCheckEnabled","navigatorTitle":[{"kind":"identifier","text":"doctorCheckEnabled"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"doctorCheckEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"kind":"symbol","type":"topic","abstract":[],"title":"PerimeterX_SDK","role":"collection","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PXPolicy","kind":"identifier"}],"abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK."}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PXPolicy"}],"title":"PXPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/doctorCheckEnabled":{"navigatorTitle":[{"text":"doctorCheckEnabled","kind":"identifier"}],"title":"doctorCheckEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctorCheckEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Set this property to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" to enable the "},{"type":"codeVoice","code":"Doctor App"},{"type":"text","text":" - a tool to verify the integration of the SDK in your app. Make sure to set this property to "},{"code":"false","type":"codeVoice"},{"text":" before deploying you app to production. Default is ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/doctorcheckenabled","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/doctorCheckEnabled","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"doctorCheckEnabled","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"doctorCheckEnabled"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"doctorCheckEnabled","kind":"identifier"}],"languages":["occ"]}]}},{"value":"PXPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","op":"replace","value":[{"text":"PXPolicy","kind":"identifier"}]},{"op":"replace","value":"doctorCheckEnabled","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1doctorCheckEnabled\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1doctorCheckEnabled\/fragments","value":[{"kind":"identifier","text":"doctorCheckEnabled"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}