{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hybridAppSupportEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/hybridAppSupportEnabled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This property is relevant only for apps that use "},{"code":"WKWebView","type":"codeVoice"},{"type":"text","text":" to load their website (which also protected by PerimeterX). By setting this property to "},{"code":"true","type":"codeVoice"},{"text":", the SDK syncs both the native and the web sessions to ensure flawless experience. Default is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":". You must set your domains with the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/set(domains:forAppId:)"},{"type":"text","text":" function to ensure the hybrid app support is working as expected."}],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/hybridappsupportenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/hybridappsupportenabled"]}],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"hybridAppSupportEnabled","kind":"identifier"}],"externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(py)hybridAppSupportEnabled","roleHeading":"Instance Property","modules":[{"name":"PerimeterX_SDK"}],"title":"hybridAppSupportEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hybridAppSupportEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/hybridAppSupportEnabled":{"type":"topic","abstract":[{"type":"text","text":"This property is relevant only for apps that use "},{"code":"WKWebView","type":"codeVoice"},{"text":" to load their website (which also protected by PerimeterX). By setting this property to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":", the SDK syncs both the native and the web sessions to ensure flawless experience. Default is "},{"code":"false","type":"codeVoice"},{"text":". You must set your domains with the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/set(domains:forAppId:)"},{"type":"text","text":" function to ensure the hybrid app support is working as expected."}],"role":"symbol","navigatorTitle":[{"text":"hybridAppSupportEnabled","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/hybridappsupportenabled","kind":"symbol","title":"hybridAppSupportEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hybridAppSupportEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/hybridAppSupportEnabled"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/urlRequestInterceptionType":{"kind":"symbol","title":"urlRequestInterceptionType","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/urlrequestinterceptiontype","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlRequestInterceptionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PXPolicyUrlRequestInterceptionType","preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType"}],"abstract":[{"type":"text","text":"Decide how the SDK should handle URL requests. Default is "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlRequestInterceptionType"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"title":"PXPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK."}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PXPolicy"}],"navigatorTitle":[{"kind":"identifier","text":"PXPolicy"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/none":{"kind":"symbol","type":"topic","title":"PXPolicyUrlRequestInterceptionType.none","abstract":[{"text":"The SDK does not intercept URL requests at all.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeNone","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"kind":"symbol","type":"topic","title":"PerimeterX_SDK","abstract":[],"url":"\/documentation\/perimeterx_sdk","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/set(domains:forAppId:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"text":"(","kind":"text"},{"text":"domains","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">, "},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/set(domains:forappid:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/set(domains:forAppId:)","abstract":[{"type":"text","text":"Use this function to register domains which your app interact with. The SDK (when the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType","isActive":true,"type":"reference"},{"type":"text","text":" is set to any value rather than "},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","type":"reference"},{"text":") is intercepting URL requests to those domains only. If you do not set domain, the SDK will intercept all URL requests. In addition, the SDK (when ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/hybridAppSupportEnabled","type":"reference","isActive":true},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"text":") is setting cookies in your web views in order to sync between the native and the web sessions. However, the SDK will set cookies only for domains that are set in this property. Therefore, you must set your domains to enable hybrid app support. Example: for the website ","type":"text"},{"code":"www.google.com","type":"codeVoice"},{"type":"text","text":" you should set the domain: "},{"code":"google.com","type":"codeVoice"},{"text":".","type":"text"}],"title":"set(domains:forAppId:)","navigatorTitle":[{"text":"setWithDomains:forAppId:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"hybridAppSupportEnabled","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hybridAppSupportEnabled"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hybridAppSupportEnabled"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"hybridAppSupportEnabled","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1hybridAppSupportEnabled\/title"},{"value":[{"text":"hybridAppSupportEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1hybridAppSupportEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1urlRequestInterceptionType\/title","value":"urlRequestInterceptionType"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1urlRequestInterceptionType\/fragments","value":[{"text":"urlRequestInterceptionType","kind":"identifier"}],"op":"replace"},{"value":"PXPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","value":[{"text":"PXPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/navigatorTitle","value":[{"text":"PXPolicy","kind":"identifier"}]},{"op":"replace","value":"PXPolicyUrlRequestInterceptionTypeNone","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/title"},{"value":[{"text":"PXPolicyUrlRequestInterceptionTypeNone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1set(domains:forAppId:)\/title","value":"setWithDomains:forAppId:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1set(domains:forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setWithDomains:forAppId:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}