{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"abstract":[{"type":"text","text":"Set this to false before calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)"},{"type":"text","text":" fucntion in order to disable requests interception."}],"metadata":{"externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(cpy)requestsInterceptedAutomaticallyEnabled","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requestsInterceptedAutomaticallyEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"PerimeterX_SDK"}],"roleHeading":"Type Property","role":"symbol","title":"requestsInterceptedAutomaticallyEnabled","navigatorTitle":[{"text":"requestsInterceptedAutomaticallyEnabled","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/requestsinterceptedautomaticallyenabled-c.type.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/requestsinterceptedautomaticallyenabled-c.type.property"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/requestsInterceptedAutomaticallyEnabled-c.type.property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestsInterceptedAutomaticallyEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","url":"\/documentation\/perimeterx_sdk\/pxpolicy","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PXPolicy","kind":"identifier"}],"abstract":[{"type":"text","text":"The policy that defines the behaviour of the SDK."}],"title":"PXPolicy","navigatorTitle":[{"kind":"identifier","text":"PXPolicy"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"abstract":[{"type":"image","identifier":"PerimeterX.png"}],"url":"\/documentation\/perimeterx_sdk","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","title":"PerimeterX_SDK","role":"collection","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:enableDoctorCheck:completion:)":{"kind":"symbol","abstract":[{"text":"Start the PerimeterX SDK.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:enabledoctorcheck:completion:)","title":"start(appId:delegate:enableDoctorCheck:completion:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:enableDoctorCheck:completion:"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate","kind":"typeIdentifier","text":"PerimeterXDelegate"},{"kind":"text","text":"?, "},{"text":"enableDoctorCheck","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/requestsInterceptedAutomaticallyEnabled-c.type.property":{"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/requestsinterceptedautomaticallyenabled-c.type.property","title":"requestsInterceptedAutomaticallyEnabled","abstract":[{"type":"text","text":"Set this to false before calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)"},{"type":"text","text":" fucntion in order to disable requests interception."}],"kind":"symbol","navigatorTitle":[{"text":"requestsInterceptedAutomaticallyEnabled","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/requestsInterceptedAutomaticallyEnabled-c.type.property","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestsInterceptedAutomaticallyEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"requestsInterceptedAutomaticallyEnabled","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"requestsInterceptedAutomaticallyEnabled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"requestsInterceptedAutomaticallyEnabled","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","value":"PXPolicy"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","value":[{"kind":"identifier","text":"PXPolicy"}],"op":"replace"},{"op":"replace","value":"startWithAppId:delegate:enableDoctorCheck:completion:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:enableDoctorCheck:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:enableDoctorCheck:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"startWithAppId:delegate:enableDoctorCheck:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1requestsInterceptedAutomaticallyEnabled-c.type.property\/title","value":"requestsInterceptedAutomaticallyEnabled"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1requestsInterceptedAutomaticallyEnabled-c.type.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"requestsInterceptedAutomaticallyEnabled"}]}]}]}