{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/set(domains:forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/set(domains:forappid:)"]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setWithDomains:forAppId:"}],"title":"set(domains:forAppId:)","roleHeading":"Instance Method","externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(im)setWithDomains:forAppId:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"set"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"domains"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"PerimeterX_SDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/set(domains:forAppId:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"text":"domains","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":" "},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"domains","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"List if your domains."}]}]},{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"text":"The AppID of your account.","type":"text"}]}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Use this function to register domains which your app interact with. The SDK (when the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType"},{"type":"text","text":" is set to any value rather than "},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","type":"reference"},{"type":"text","text":") is intercepting URL requests to those domains only. If you do not set domain, the SDK will intercept all URL requests. In addition, the SDK (when "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/hybridAppSupportEnabled","isActive":true},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":") is setting cookies in your web views in order to sync between the native and the web sessions. However, the SDK will set cookies only for domains that are set in this property. Therefore, you must set your domains to enable hybrid app support. Example: for the website "},{"code":"www.google.com","type":"codeVoice"},{"type":"text","text":" you should set the domain: "},{"code":"google.com","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/hybridAppSupportEnabled":{"type":"topic","abstract":[{"type":"text","text":"This property is relevant only for apps that use "},{"code":"WKWebView","type":"codeVoice"},{"text":" to load their website (which also protected by PerimeterX). By setting this property to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":", the SDK syncs both the native and the web sessions to ensure flawless experience. Default is "},{"code":"false","type":"codeVoice"},{"text":". You must set your domains with the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/set(domains:forAppId:)"},{"type":"text","text":" function to ensure the hybrid app support is working as expected."}],"role":"symbol","navigatorTitle":[{"text":"hybridAppSupportEnabled","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/hybridappsupportenabled","kind":"symbol","title":"hybridAppSupportEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hybridAppSupportEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/hybridAppSupportEnabled"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/intercept":{"kind":"symbol","type":"topic","title":"PXPolicyUrlRequestInterceptionType.intercept","abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"text":" ","type":"text"},{"text":"The SDK can intercept those types of requests:","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/intercept","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"intercept"}],"navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeIntercept"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/set(domains:forAppId:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"text":"(","kind":"text"},{"text":"domains","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">, "},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/set(domains:forappid:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/set(domains:forAppId:)","abstract":[{"type":"text","text":"Use this function to register domains which your app interact with. The SDK (when the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType","isActive":true,"type":"reference"},{"type":"text","text":" is set to any value rather than "},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","type":"reference"},{"text":") is intercepting URL requests to those domains only. If you do not set domain, the SDK will intercept all URL requests. In addition, the SDK (when ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/hybridAppSupportEnabled","type":"reference","isActive":true},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"text":") is setting cookies in your web views in order to sync between the native and the web sessions. However, the SDK will set cookies only for domains that are set in this property. Therefore, you must set your domains to enable hybrid app support. Example: for the website ","type":"text"},{"code":"www.google.com","type":"codeVoice"},{"type":"text","text":" you should set the domain: "},{"code":"google.com","type":"codeVoice"},{"text":".","type":"text"}],"title":"set(domains:forAppId:)","navigatorTitle":[{"text":"setWithDomains:forAppId:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"title":"PXPolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK."}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PXPolicy"}],"navigatorTitle":[{"kind":"identifier","text":"PXPolicy"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/urlRequestInterceptionType":{"kind":"symbol","title":"urlRequestInterceptionType","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/urlrequestinterceptiontype","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlRequestInterceptionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PXPolicyUrlRequestInterceptionType","preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType"}],"abstract":[{"type":"text","text":"Decide how the SDK should handle URL requests. Default is "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlRequestInterceptionType"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/none":{"kind":"symbol","type":"topic","title":"PXPolicyUrlRequestInterceptionType.none","abstract":[{"text":"The SDK does not intercept URL requests at all.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeNone","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"kind":"symbol","type":"topic","title":"PerimeterX_SDK","abstract":[],"url":"\/documentation\/perimeterx_sdk","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setWithDomains:forAppId:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setWithDomains:forAppId:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setWithDomains:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSSet<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"domains"},{"kind":"text","text":" "},{"kind":"identifier","text":"forAppId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"List if your domains.","type":"text"}],"type":"paragraph"}],"name":"domains"},{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AppID of your account."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"hybridAppSupportEnabled","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1hybridAppSupportEnabled\/title"},{"value":[{"text":"hybridAppSupportEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1hybridAppSupportEnabled\/fragments"},{"value":"PXPolicyUrlRequestInterceptionTypeIntercept","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeIntercept"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1set(domains:forAppId:)\/title","value":"setWithDomains:forAppId:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setWithDomains:forAppId:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1set(domains:forAppId:)\/fragments"},{"op":"replace","value":"PXPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title"},{"value":[{"kind":"identifier","text":"PXPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PXPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1urlRequestInterceptionType\/title","value":"urlRequestInterceptionType","op":"replace"},{"op":"replace","value":[{"text":"urlRequestInterceptionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1urlRequestInterceptionType\/fragments"},{"value":"PXPolicyUrlRequestInterceptionTypeNone","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/fragments"}]}]}