{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlRequestInterceptionType"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","kind":"typeIdentifier","text":"PXPolicyUrlRequestInterceptionType","preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"]]},"abstract":[{"text":"Decide how the SDK should handle URL requests. Default is ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","isActive":true},{"text":".","type":"text"}],"metadata":{"externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy(py)urlRequestInterceptionType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlRequestInterceptionType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType","kind":"typeIdentifier","text":"PXPolicyUrlRequestInterceptionType"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"urlRequestInterceptionType"}],"title":"urlRequestInterceptionType","modules":[{"name":"PerimeterX_SDK"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/urlrequestinterceptiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy\/urlrequestinterceptiontype"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/perimeterx_sdk","title":"PerimeterX_SDK"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/intercept":{"type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/intercept","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","abstract":[{"text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}],"title":"PXPolicyUrlRequestInterceptionType.intercept","role":"symbol","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"intercept","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType":{"type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","abstract":[{"text":"The URL request interception type.","type":"text"}],"title":"PXPolicyUrlRequestInterceptionType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/urlRequestInterceptionType":{"type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/urlrequestinterceptiontype","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType","abstract":[{"text":"Decide how the SDK should handle URL requests. Default is ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","isActive":true},{"text":".","type":"text"}],"title":"urlRequestInterceptionType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"urlRequestInterceptionType"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"urlRequestInterceptionType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType","text":"PXPolicyUrlRequestInterceptionType"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","role":"symbol","title":"PXPolicy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PXPolicy"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy","navigatorTitle":[{"text":"PXPolicy","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"urlRequestInterceptionType"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"urlRequestInterceptionType"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType","text":"PXPolicyUrlRequestInterceptionType"},{"text":" ","kind":"text"},{"text":"urlRequestInterceptionType","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/title","value":"PXPolicyUrlRequestInterceptionTypeIntercept"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/fragments","value":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/title","value":"PXPolicyUrlRequestInterceptionType"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/fragments","value":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1urlRequestInterceptionType\/title","value":"urlRequestInterceptionType"},{"value":[{"text":"urlRequestInterceptionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1urlRequestInterceptionType\/fragments"},{"value":"PXPolicy","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","value":[{"kind":"identifier","text":"PXPolicy"}],"op":"replace"}]}]}