{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxversionstring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxversionstring"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXVersionString"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerimeterXVersionString"},{"text":": <<error type>>","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"PerimeterX_SDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerimeterXVersionString"},{"text":": <<error type>>","kind":"text"}],"roleHeading":"Global Variable","title":"PerimeterXVersionString","role":"symbol","symbolKind":"var","externalID":"c:@PerimeterXVersionString","navigatorTitle":[{"kind":"identifier","text":"PerimeterXVersionString"}]},"abstract":[{"type":"text","text":"Project version string for PerimeterX."}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"title":"PerimeterX_SDK","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/perimeterx_sdk"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXVersionString":{"title":"PerimeterXVersionString","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PerimeterXVersionString"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxversionstring","type":"topic","abstract":[{"text":"Project version string for PerimeterX.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerimeterXVersionString","kind":"identifier"},{"kind":"text","text":": <<error type>>"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXVersionString"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PerimeterXVersionString","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"value":[{"kind":"identifier","text":"PerimeterXVersionString"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"text":"unsigned char","kind":"typeIdentifier","preciseIdentifier":"c:c"},{"text":" ","kind":"text"},{"text":"PerimeterXVersionString","kind":"identifier"},{"text":"[];","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXVersionString\/title","value":"PerimeterXVersionString","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PerimeterXVersionString"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXVersionString\/fragments"}]}]}