{"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXVersionNumber","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"PerimeterXVersionNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Project version number for PerimeterX."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxversionnumber"]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterxversionnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"]]},"kind":"symbol","metadata":{"roleHeading":"Global Variable","navigatorTitle":[{"text":"PerimeterXVersionNumber","kind":"identifier"}],"externalID":"c:@PerimeterXVersionNumber","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"PerimeterXVersionNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"symbolKind":"var","title":"PerimeterXVersionNumber","role":"symbol","modules":[{"name":"PerimeterX_SDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXVersionNumber":{"title":"PerimeterXVersionNumber","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterXVersionNumber"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxversionnumber","abstract":[{"type":"text","text":"Project version number for PerimeterX."}],"navigatorTitle":[{"kind":"identifier","text":"PerimeterXVersionNumber"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXVersionNumber"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"abstract":[],"title":"PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","value":"PerimeterXVersionNumber","op":"replace"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PerimeterXVersionNumber"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"PerimeterXVersionNumber","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PerimeterXVersionNumber","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXVersionNumber\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXVersionNumber\/fragments","value":[{"text":"PerimeterXVersionNumber","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}