{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode"]}],"metadata":{"role":"symbol","symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"PerimeterX_SDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerimeterXErrorCode","kind":"identifier"}],"externalID":"c:@M@PerimeterX_SDK@E@PerimeterXErrorCode","title":"PerimeterXErrorCode","navigatorTitle":[{"text":"PerimeterXErrorCode","kind":"identifier"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerimeterXErrorCode","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeCancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeSolved","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/httpBodyInputStreamReadFailed","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/internalError","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/invalidAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/missingAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/requestWasBlocked","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startCalledMoreThanOnce","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startNotCalledOnMainThread","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startWasNotCalled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/tokenWasNotGenerated"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/Equatable-Implementations","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/RawRepresentable-Implementations":{"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/rawrepresentable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/tokenWasNotGenerated":{"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/tokenwasnotgenerated","kind":"symbol","navigatorTitle":[{"text":"PerimeterXErrorCodeTokenWasNotGenerated","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/tokenWasNotGenerated","abstract":[{"type":"text","text":"The SDK failed to generate token. Make sure the AppID is set correctly."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenWasNotGenerated","kind":"identifier"}],"type":"topic","title":"PerimeterXErrorCode.tokenWasNotGenerated","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/internalError":{"type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCodeInternalError","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}],"title":"PerimeterXErrorCode.internalError","role":"symbol","abstract":[{"type":"text","text":"Internal error in the SDK."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/internalError","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/internalerror","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/missingAppId":{"type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCodeMissingAppId","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"missingAppId","kind":"identifier"}],"title":"PerimeterXErrorCode.missingAppId","role":"symbol","abstract":[{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","isActive":true},{"text":" or ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)"},{"text":" functions were called without any AppID.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/missingAppId","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/missingappid","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/startWasNotCalled":{"type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCodeStartWasNotCalled","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startWasNotCalled","kind":"identifier"}],"title":"PerimeterXErrorCode.startWasNotCalled","role":"symbol","abstract":[{"text":"The SDK failed to perform the operation. Make sure to call the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)"},{"text":" function.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startWasNotCalled","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/startwasnotcalled","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/startNotCalledOnMainThread":{"type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCodeStartNotCalledOnMainThread","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startNotCalledOnMainThread","kind":"identifier"}],"title":"PerimeterXErrorCode.startNotCalledOnMainThread","role":"symbol","abstract":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","isActive":true,"type":"reference"},{"text":" or ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","type":"reference"},{"type":"text","text":" functions were called not on the main thread."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startNotCalledOnMainThread","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/startnotcalledonmainthread","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/challengeSolved":{"type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCodeChallengeSolved","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeSolved","kind":"identifier"}],"title":"PerimeterXErrorCode.challengeSolved","role":"symbol","abstract":[{"type":"text","text":"Challenge was solved by the user."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeSolved","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/challengesolved","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/requestWasBlocked":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestWasBlocked","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCodeRequestWasBlocked"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/requestWasBlocked","title":"PerimeterXErrorCode.requestWasBlocked","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/requestwasblocked","type":"topic","abstract":[{"type":"text","text":"URL request was blocked by PerimeterX."}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/httpBodyInputStreamReadFailed":{"type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCodeHttpBodyInputStreamReadFailed","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpBodyInputStreamReadFailed","kind":"identifier"}],"title":"PerimeterXErrorCode.httpBodyInputStreamReadFailed","role":"symbol","abstract":[{"type":"text","text":"Failed to read body from input stream of the request."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/httpBodyInputStreamReadFailed","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/httpbodyinputstreamreadfailed","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/SH":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:policy:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","type":"topic","abstract":[{"type":"text","text":"Start the SDK."}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:policy:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PerimeterXDelegate","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","text":"PXPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"role":"symbol","kind":"symbol","title":"start(appId:delegate:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/invalidAppId":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAppId"}],"title":"PerimeterXErrorCode.invalidAppId","kind":"symbol","abstract":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","type":"reference","isActive":true},{"text":" or ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)"},{"type":"text","text":" functions were called with invalid AppID."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCodeInvalidAppId"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/invalidAppId","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/invalidappid"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"type":"topic","url":"\/documentation\/perimeterx_sdk","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"title":"PerimeterX_SDK","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/init(rawValue:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","role":"symbol","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/init(rawValue:)","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/init(rawvalue:)","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/startCalledMoreThanOnce":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCodeStartCalledMoreThanOnce"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCalledMoreThanOnce"}],"title":"PerimeterXErrorCode.startCalledMoreThanOnce","role":"symbol","abstract":[{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","isActive":true},{"type":"text","text":" or "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","isActive":true,"type":"reference"},{"type":"text","text":" functions were called more than once."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startCalledMoreThanOnce","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/startcalledmorethanonce","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode":{"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode","kind":"symbol","navigatorTitle":[{"text":"PerimeterXErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerimeterXErrorCode","kind":"identifier"}],"type":"topic","title":"PerimeterXErrorCode","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/equatable-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/Equatable-Implementations"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appIds:delegate:policy:)":{"kind":"symbol","abstract":[{"type":"text","text":"Start the SDK."}],"title":"start(appIds:delegate:policy:)","url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appids:delegate:policy:)","navigatorTitle":[{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PerimeterXDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},{"text":"?, ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","text":"PXPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)"},"doc://com.perimeterx.mobile-sdk/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SY"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/challengeCancelled":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"challengeCancelled"}],"type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCodeChallengeCancelled","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/challengecancelled","abstract":[{"type":"text","text":"Challenge was cancelled."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeCancelled","title":"PerimeterXErrorCode.challengeCancelled","role":"symbol"},"doc://com.perimeterx.mobile-sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PerimeterXErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PerimeterXErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PerimeterXErrorCode"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeCancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeSolved","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/httpBodyInputStreamReadFailed","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/internalError","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/invalidAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/missingAppId","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/requestWasBlocked","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startCalledMoreThanOnce","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startNotCalledOnMainThread","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startWasNotCalled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/tokenWasNotGenerated"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerimeterXErrorCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PerimeterXErrorCodeTokenWasNotGenerated","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1tokenWasNotGenerated\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1tokenWasNotGenerated\/fragments","value":[{"kind":"identifier","text":"PerimeterXErrorCodeTokenWasNotGenerated"}]},{"value":"PerimeterXErrorCodeInternalError","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1internalError\/title"},{"value":[{"text":"PerimeterXErrorCodeInternalError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1internalError\/fragments"},{"value":"PerimeterXErrorCodeMissingAppId","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1missingAppId\/title","op":"replace"},{"value":[{"text":"PerimeterXErrorCodeMissingAppId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1missingAppId\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1startWasNotCalled\/title","op":"replace","value":"PerimeterXErrorCodeStartWasNotCalled"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1startWasNotCalled\/fragments","value":[{"text":"PerimeterXErrorCodeStartWasNotCalled","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1startNotCalledOnMainThread\/title","value":"PerimeterXErrorCodeStartNotCalledOnMainThread"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1startNotCalledOnMainThread\/fragments","value":[{"text":"PerimeterXErrorCodeStartNotCalledOnMainThread","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeSolved\/title","op":"replace","value":"PerimeterXErrorCodeChallengeSolved"},{"value":[{"kind":"identifier","text":"PerimeterXErrorCodeChallengeSolved"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeSolved\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1requestWasBlocked\/title","op":"replace","value":"PerimeterXErrorCodeRequestWasBlocked"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1requestWasBlocked\/fragments","op":"replace","value":[{"text":"PerimeterXErrorCodeRequestWasBlocked","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1httpBodyInputStreamReadFailed\/title","value":"PerimeterXErrorCodeHttpBodyInputStreamReadFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1httpBodyInputStreamReadFailed\/fragments","value":[{"text":"PerimeterXErrorCodeHttpBodyInputStreamReadFailed","kind":"identifier"}]},{"value":"startWithAppId:delegate:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1invalidAppId\/title","value":"PerimeterXErrorCodeInvalidAppId"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1invalidAppId\/fragments","op":"replace","value":[{"kind":"identifier","text":"PerimeterXErrorCodeInvalidAppId"}]},{"value":"PerimeterXErrorCodeStartCalledMoreThanOnce","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1startCalledMoreThanOnce\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1startCalledMoreThanOnce\/fragments","value":[{"text":"PerimeterXErrorCodeStartCalledMoreThanOnce","kind":"identifier"}]},{"value":"PerimeterXErrorCode","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PerimeterXErrorCode"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/fragments"},{"value":"startWithAppIds:delegate:policy:error:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appIds:delegate:policy:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appIds:delegate:policy:)\/fragments","op":"replace"},{"op":"replace","value":"PerimeterXErrorCodeChallengeCancelled","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeCancelled\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeCancelled\/fragments","op":"replace","value":[{"kind":"identifier","text":"PerimeterXErrorCodeChallengeCancelled"}]}]}]}