{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerimeterXDelegate"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"PerimeterX protocol","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"]]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterxdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxdelegate"]}],"kind":"symbol","metadata":{"roleHeading":"Protocol","title":"PerimeterXDelegate","modules":[{"name":"PerimeterX_SDK"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerimeterXDelegate","kind":"identifier"}],"symbolKind":"protocol","navigatorTitle":[{"text":"PerimeterXDelegate","kind":"identifier"}],"externalID":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidChallengeCancelled(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidChallengeSolved(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidRequestBlocked(url:appId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxHeadersWereUpdated(headers:forAppId:)"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate/perimeterxDidChallengeCancelled(forAppId:)":{"url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidchallengecancelled(forappid:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"perimeterxDidChallengeCancelled","kind":"identifier"},{"kind":"text","text":"("},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"perimeterxDidChallengeCancelled(forAppId:)","kind":"symbol","navigatorTitle":[{"text":"perimeterxDidChallengeCancelledForAppId:","kind":"identifier"}],"required":true,"abstract":[{"text":"Called when the challenge was cancelled.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidChallengeCancelled(forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/headersForURLRequest(forAppId:)":{"url":"\/documentation\/perimeterx_sdk\/perimeterx\/headersforurlrequest(forappid:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headersForURLRequest","kind":"identifier"},{"kind":"text","text":"("},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?","kind":"text"}],"role":"symbol","title":"headersForURLRequest(forAppId:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"headersForURLRequestForAppId:"}],"abstract":[{"text":"Returns HTTP headers that should be added to the URL request.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/headersForURLRequest(forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate/perimeterxDidRequestBlocked(url:appId:)":{"url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidrequestblocked(url:appid:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perimeterxDidRequestBlocked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","title":"perimeterxDidRequestBlocked(url:appId:)","kind":"symbol","navigatorTitle":[{"text":"perimeterxDidRequestBlockedWithUrl:appId:","kind":"identifier"}],"required":true,"abstract":[{"text":"Called when a request was blocked.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidRequestBlocked(url:appId:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate":{"type":"topic","title":"PerimeterXDelegate","abstract":[{"text":"PerimeterX protocol","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"PerimeterXDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerimeterXDelegate","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"kind":"symbol","role":"collection","type":"topic","title":"PerimeterX_SDK","abstract":[],"url":"\/documentation\/perimeterx_sdk","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate/perimeterxDidChallengeSolved(forAppId:)":{"url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidchallengesolved(forappid:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"perimeterxDidChallengeSolved","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"perimeterxDidChallengeSolved(forAppId:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"perimeterxDidChallengeSolvedForAppId:"}],"required":true,"abstract":[{"type":"text","text":"Called when the challenge was solved."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidChallengeSolved(forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate/perimeterxHeadersWereUpdated(headers:forAppId:)":{"type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxheaderswereupdated(headers:forappid:)","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxHeadersWereUpdated(headers:forAppId:)","title":"perimeterxHeadersWereUpdated(headers:forAppId:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"perimeterxHeadersWereUpdatedWithHeaders:forAppId:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"perimeterxHeadersWereUpdated","kind":"identifier"},{"text":"(","kind":"text"},{"text":"headers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called when the HTTP headers were changed. You may store and use those headers instead of calling the "},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/headersForURLRequest(forAppId:)","type":"reference"},{"type":"text","text":" function for every URL request."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PerimeterXDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"kind":"identifier","text":"PerimeterXDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PerimeterXDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidChallengeCancelled(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidChallengeSolved(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidRequestBlocked(url:appId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxHeadersWereUpdated(headers:forAppId:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerimeterXDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}]}},{"value":"perimeterxDidChallengeCancelledForAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidChallengeCancelled(forAppId:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"perimeterxDidChallengeCancelledForAppId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidChallengeCancelled(forAppId:)\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1headersForURLRequest(forAppId:)\/title","value":"headersForURLRequestForAppId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1headersForURLRequest(forAppId:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"headersForURLRequestForAppId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidRequestBlocked(url:appId:)\/title","value":"perimeterxDidRequestBlockedWithUrl:appId:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidRequestBlocked(url:appId:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"perimeterxDidRequestBlockedWithUrl:appId:","kind":"identifier"}]},{"op":"replace","value":"PerimeterXDelegate","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/title"},{"op":"replace","value":[{"text":"PerimeterXDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidChallengeSolved(forAppId:)\/title","value":"perimeterxDidChallengeSolvedForAppId:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"perimeterxDidChallengeSolvedForAppId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidChallengeSolved(forAppId:)\/fragments"},{"op":"replace","value":"perimeterxHeadersWereUpdatedWithHeaders:forAppId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxHeadersWereUpdated(headers:forAppId:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"perimeterxHeadersWereUpdatedWithHeaders:forAppId:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxHeadersWereUpdated(headers:forAppId:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}