{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/cancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/solved"]},{"title":"Initializers","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/Equatable-Implementations","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/SY"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterXChallengeResult"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult","interfaceLanguage":"swift"},"abstract":[{"text":"Challenge result.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"modules":[{"name":"PerimeterX_SDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterXChallengeResult"}],"symbolKind":"enum","externalID":"c:@M@PerimeterX_SDK@E@PerimeterXChallengeResult","navigatorTitle":[{"kind":"identifier","text":"PerimeterXChallengeResult"}],"role":"symbol","roleHeading":"Enumeration","title":"PerimeterXChallengeResult"},"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterxchallengeresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterxchallengeresult"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"]]},"references":{"doc://com.perimeterx.mobile-sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult/Equatable-Implementations":{"type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/equatable-implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult/cancelled":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/cancelled","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/cancelled","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"navigatorTitle":[{"kind":"identifier","text":"PerimeterXChallengeResultCancelled"}],"abstract":[{"type":"text","text":"Challenge was cancelled."}],"role":"symbol","title":"PerimeterXChallengeResult.cancelled"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult/init(rawValue:)":{"role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/init(rawvalue:)","title":"init(rawValue:)","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/init(rawValue:)"},"doc://com.perimeterx.mobile-sdk/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SY"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"url":"\/documentation\/perimeterx_sdk","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","abstract":[],"type":"topic","title":"PerimeterX_SDK"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult":{"role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult","title":"PerimeterXChallengeResult","type":"topic","abstract":[{"text":"Challenge result.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerimeterXChallengeResult"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult","navigatorTitle":[{"text":"PerimeterXChallengeResult","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/rawrepresentable-implementations","type":"topic","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult/solved":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PerimeterXChallengeResultSolved"}],"type":"topic","title":"PerimeterXChallengeResult.solved","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/solved","abstract":[{"type":"text","text":"Challenge was solved."}],"url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/solved","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"solved"}]},"doc://com.perimeterx.mobile-sdk/SQ":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PerimeterXChallengeResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"PerimeterXChallengeResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"PerimeterXChallengeResult"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/cancelled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/solved"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PerimeterXChallengeResult","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult~1cancelled\/title","value":"PerimeterXChallengeResultCancelled"},{"value":[{"text":"PerimeterXChallengeResultCancelled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult~1cancelled\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/title","op":"replace","value":"PerimeterXChallengeResult"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/fragments","value":[{"kind":"identifier","text":"PerimeterXChallengeResult"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult~1solved\/title","op":"replace","value":"PerimeterXChallengeResultSolved"},{"value":[{"text":"PerimeterXChallengeResultSolved","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult~1solved\/fragments","op":"replace"}]}]}