{"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/canHandleResponse(response:data:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/handleResponse(response:data:forAppId:callback:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/headersForURLRequest(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isChallengeCancelledError(error:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isChallengeSolvedError(error:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isRequestBlockedError(error:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerOutgoingUrlRequest(url:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/sdkVersion()","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setAdditionalData(parameters:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setCustomParameters(parameters:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setUserId(userId:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/vid(forAppId:)"],"title":"Type Methods"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH"],"title":"Conforms To","kind":"relationships"}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"class","externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX","title":"PerimeterX","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterX"}],"navigatorTitle":[{"kind":"identifier","text":"PerimeterX"}],"roleHeading":"Class","modules":[{"name":"PerimeterX_SDK"}],"role":"symbol"},"abstract":[{"type":"text","text":"PerimeterX main class. You should interact with it in order to setup and start the SDK."}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx"]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterx"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PerimeterX","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/handleResponse(response:data:forAppId:callback:)":{"abstract":[{"type":"text","text":"This function handles the URL request’s response and presents the block screen, if necessary."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleResponse"},{"text":"(","kind":"text"},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@PerimeterX_SDK@E@PerimeterXChallengeResult","text":"PerimeterXChallengeResult","kind":"typeIdentifier"},{"kind":"text","text":") -> ())?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"handleResponseWithResponse:data:forAppId:callback:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/handleresponse(response:data:forappid:callback:)","title":"handleResponse(response:data:forAppId:callback:)","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/handleResponse(response:data:forAppId:callback:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/setUserId(userId:forAppId:)":{"kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/setuserid(userid:forappid:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setUserId","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"setUserIdWithUserId:forAppId:error:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setUserId(userId:forAppId:)","type":"topic","abstract":[{"type":"text","text":"Calling this method with non-"},{"code":"null","type":"codeVoice"},{"type":"text","text":" "},{"type":"codeVoice","code":"userId"},{"text":" will start the Account Defender feature.","type":"text"}],"title":"setUserId(userId:forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"kind":"symbol","type":"topic","abstract":[],"title":"PerimeterX_SDK","role":"collection","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/challengeSolved":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeSolved","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"challengeSolved","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/challengesolved","title":"PerimeterXErrorCode.challengeSolved","abstract":[{"type":"text","text":"Challenge was solved by the user."}],"navigatorTitle":[{"text":"PerimeterXErrorCodeChallengeSolved","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/requestWasBlocked":{"title":"PerimeterXErrorCode.requestWasBlocked","abstract":[{"type":"text","text":"URL request was blocked by PerimeterX."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/requestWasBlocked","role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/requestwasblocked","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"requestWasBlocked","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCodeRequestWasBlocked","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/isRequestBlockedError(error:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRequestBlockedError"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isRequestBlockedError(error:)","title":"isRequestBlockedError(error:)","navigatorTitle":[{"text":"isRequestBlockedErrorWithError:","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/isrequestblockederror(error:)","abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the error is ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/requestWasBlocked"},{"type":"text","text":" error."}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/setCustomParameters(parameters:forAppId:)":{"navigatorTitle":[{"kind":"identifier","text":"setCustomParametersWithParameters:forAppId:error:"}],"title":"setCustomParameters(parameters:forAppId:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setCustomParameters(parameters:forAppId:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setCustomParameters","kind":"identifier"},{"kind":"text","text":"("},{"text":"parameters","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/setcustomparameters(parameters:forappid:)","kind":"symbol","type":"topic","abstract":[{"text":"Set custom parameters for given AppID.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP"},"doc://com.perimeterx.mobile-sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ"},"doc://com.perimeterx.mobile-sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"title":"PerimeterX","abstract":[{"type":"text","text":"PerimeterX main class. You should interact with it in order to setup and start the SDK."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PerimeterX","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PerimeterX","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appIds:delegate:policy:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"text":"appIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate","text":"PerimeterXDelegate"},{"kind":"text","text":"?, "},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PXPolicy","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appids:delegate:policy:)","title":"start(appIds:delegate:policy:)","abstract":[{"text":"Start the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:delegate:policy:error:"}]},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/headersForURLRequest(forAppId:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headersForURLRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"headersForURLRequestForAppId:","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/headersforurlrequest(forappid:)","type":"topic","title":"headersForURLRequest(forAppId:)","abstract":[{"text":"Returns HTTP headers that should be added to the URL request.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/headersForURLRequest(forAppId:)"},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/canHandleResponse(response:data:forAppId:)":{"abstract":[{"type":"text","text":"This function checks if the SDK can handle the URL request’s response and presents the block screen."}],"navigatorTitle":[{"kind":"identifier","text":"canHandleResponseWithResponse:data:forAppId:"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/canhandleresponse(response:data:forappid:)","title":"canHandleResponse(response:data:forAppId:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandleResponse"},{"text":"(","kind":"text"},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/canHandleResponse(response:data:forAppId:)","type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/init","type":"topic","title":"init","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/init"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/registerOutgoingUrlRequest(url:forAppId:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOutgoingUrlRequestWithUrl:forAppId:error:"}],"kind":"symbol","title":"registerOutgoingUrlRequest(url:forAppId:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerOutgoingUrlRequest"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Provide outgoing URL request to the Account Defender feature."}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/registeroutgoingurlrequest(url:forappid:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerOutgoingUrlRequest(url:forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:policy:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","kind":"symbol","abstract":[{"text":"Start the SDK.","type":"text"}],"title":"start(appId:delegate:policy:)","type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:policy:)","navigatorTitle":[{"text":"startWithAppId:delegate:policy:error:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate","text":"PerimeterXDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"policy","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PXPolicy","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/sdkVersion()":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/sdkVersion()","url":"\/documentation\/perimeterx_sdk\/perimeterx\/sdkversion()","kind":"symbol","type":"topic","title":"sdkVersion()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkVersion","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sdkVersion","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the PerimeterX SDK version."}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/setAdditionalData(parameters:forAppId:)":{"url":"\/documentation\/perimeterx_sdk\/perimeterx\/setadditionaldata(parameters:forappid:)","type":"topic","abstract":[{"type":"text","text":"Set additional data that support Account Defender for given AppID."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAdditionalData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"setAdditionalData(parameters:forAppId:)","navigatorTitle":[{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setAdditionalData(parameters:forAppId:)","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/isChallengeSolvedError(error:)":{"abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the error is "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeSolved"},{"type":"text","text":" error."}],"navigatorTitle":[{"kind":"identifier","text":"isChallengeSolvedErrorWithError:"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/ischallengesolvederror(error:)","title":"isChallengeSolvedError(error:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isChallengeSolvedError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isChallengeSolvedError(error:)","type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/isChallengeCancelledError(error:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isChallengeCancelledError","kind":"identifier"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"text":" if the error is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeCancelled"},{"text":" error.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/ischallengecancellederror(error:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"isChallengeCancelledErrorWithError:","kind":"identifier"}],"title":"isChallengeCancelledError(error:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isChallengeCancelledError(error:)","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/vid(forAppId:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vid"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/vid(forAppId:)","title":"vid(forAppId:)","kind":"symbol","type":"topic","abstract":[{"text":"Get the VID for given AppID.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/vid(forappid:)","role":"symbol","navigatorTitle":[{"text":"vidForAppId:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/challengeCancelled":{"navigatorTitle":[{"text":"PerimeterXErrorCodeChallengeCancelled","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/challengecancelled","kind":"symbol","abstract":[{"text":"Challenge was cancelled.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeCancelled","title":"PerimeterXErrorCode.challengeCancelled","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"challengeCancelled","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PerimeterX"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PerimeterX"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PerimeterX","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/init"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/canHandleResponse(response:data:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/handleResponse(response:data:forAppId:callback:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/headersForURLRequest(forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isChallengeCancelledError(error:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isChallengeSolvedError(error:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isRequestBlockedError(error:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerOutgoingUrlRequest(url:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/sdkVersion()","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setAdditionalData(parameters:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setCustomParameters(parameters:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setUserId(userId:forAppId:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/vid(forAppId:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerimeterX","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1handleResponse(response:data:forAppId:callback:)\/title","op":"replace","value":"handleResponseWithResponse:data:forAppId:callback:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1handleResponse(response:data:forAppId:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleResponseWithResponse:data:forAppId:callback:"}]},{"op":"replace","value":"setUserIdWithUserId:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setUserId(userId:forAppId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setUserId(userId:forAppId:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setUserIdWithUserId:forAppId:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeSolved\/title","op":"replace","value":"PerimeterXErrorCodeChallengeSolved"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeSolved\/fragments","op":"replace","value":[{"kind":"identifier","text":"PerimeterXErrorCodeChallengeSolved"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1requestWasBlocked\/title","value":"PerimeterXErrorCodeRequestWasBlocked"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1requestWasBlocked\/fragments","value":[{"text":"PerimeterXErrorCodeRequestWasBlocked","kind":"identifier"}],"op":"replace"},{"value":"isRequestBlockedErrorWithError:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1isRequestBlockedError(error:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1isRequestBlockedError(error:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"isRequestBlockedErrorWithError:"}]},{"op":"replace","value":"setCustomParametersWithParameters:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setCustomParameters(parameters:forAppId:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setCustomParameters(parameters:forAppId:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setCustomParametersWithParameters:forAppId:error:","kind":"identifier"}],"op":"replace"},{"value":"PerimeterX","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","op":"replace"},{"value":[{"text":"PerimeterX","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appIds:delegate:policy:)\/title","op":"replace","value":"startWithAppIds:delegate:policy:error:"},{"value":[{"kind":"text","text":"+ "},{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appIds:delegate:policy:)\/fragments"},{"value":"headersForURLRequestForAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1headersForURLRequest(forAppId:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1headersForURLRequest(forAppId:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"headersForURLRequestForAppId:"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1canHandleResponse(response:data:forAppId:)\/title","value":"canHandleResponseWithResponse:data:forAppId:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"canHandleResponseWithResponse:data:forAppId:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1canHandleResponse(response:data:forAppId:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1registerOutgoingUrlRequest(url:forAppId:)\/title","value":"registerOutgoingUrlRequestWithUrl:forAppId:error:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"registerOutgoingUrlRequestWithUrl:forAppId:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1registerOutgoingUrlRequest(url:forAppId:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/title","value":"startWithAppId:delegate:policy:error:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/fragments"},{"value":"sdkVersion","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1sdkVersion()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1sdkVersion()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sdkVersion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setAdditionalData(parameters:forAppId:)\/title","op":"replace","value":"setAdditionalDataWithParameters:forAppId:error:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setAdditionalData(parameters:forAppId:)\/fragments"},{"value":"isChallengeSolvedErrorWithError:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1isChallengeSolvedError(error:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1isChallengeSolvedError(error:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"isChallengeSolvedErrorWithError:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1isChallengeCancelledError(error:)\/title","op":"replace","value":"isChallengeCancelledErrorWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1isChallengeCancelledError(error:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"isChallengeCancelledErrorWithError:","kind":"identifier"}]},{"value":"vidForAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1vid(forAppId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1vid(forAppId:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"vidForAppId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeCancelled\/title","value":"PerimeterXErrorCodeChallengeCancelled","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeCancelled\/fragments","op":"replace","value":[{"kind":"identifier","text":"PerimeterXErrorCodeChallengeCancelled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}