{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Challenge type."}],"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/webView"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/Equatable-Implementations","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/RawRepresentable-Implementations"]}],"kind":"symbol","metadata":{"symbolKind":"enum","externalID":"c:@M@PerimeterX_SDK@E@PXPolicyChallengeType","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PXPolicyChallengeType","kind":"identifier"}],"title":"PXPolicyChallengeType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PXPolicyChallengeType"}],"modules":[{"name":"PerimeterX_SDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicychallengetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicychallengetype"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PXPolicyChallengeType","kind":"identifier"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/s12CaseIterableP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyChallengeType/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/perimeterx_sdk\/pxpolicychallengetype\/equatable-implementations","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/Equatable-Implementations"},"doc://com.perimeterx.mobile-sdk/SQ":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.perimeterx.mobile-sdk/SH":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyChallengeType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/init(rawValue:)","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicychallengetype\/init(rawvalue:)","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","kind":"symbol","url":"\/documentation\/perimeterx_sdk","title":"PerimeterX_SDK","type":"topic","abstract":[{"type":"image","identifier":"PerimeterX.png"}]},"doc://com.perimeterx.mobile-sdk/SY":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyChallengeType/webView":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PXPolicyChallengeTypeWebView"}],"title":"PXPolicyChallengeType.webView","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"}],"abstract":[{"type":"text","text":"WebView challenge."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/webView","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicychallengetype\/webview","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyChallengeType":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PXPolicyChallengeType"}],"navigatorTitle":[{"kind":"identifier","text":"PXPolicyChallengeType"}],"role":"symbol","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicychallengetype","title":"PXPolicyChallengeType","type":"topic","abstract":[{"text":"Challenge type.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyChallengeType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicychallengetype\/rawrepresentable-implementations","kind":"article"},"doc://com.perimeterx.mobile-sdk/s12CaseIterableP":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s12CaseIterableP","type":"unresolvable","title":"Swift.CaseIterable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"PXPolicyChallengeType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"PXPolicyChallengeType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PXPolicyChallengeType","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType\/webView"],"title":"Enumeration Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PXPolicyChallengeType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyChallengeType~1webView\/title","op":"replace","value":"PXPolicyChallengeTypeWebView"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyChallengeType~1webView\/fragments","value":[{"text":"PXPolicyChallengeTypeWebView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyChallengeType\/title","value":"PXPolicyChallengeType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyChallengeType\/fragments","value":[{"text":"PXPolicyChallengeType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}