{"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptAndRetryRequest","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptWithDelayedResponse","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/Equatable-Implementations","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/RawRepresentable-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype"]},{"paths":["\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"]]},"metadata":{"symbolKind":"enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"modules":[{"name":"PerimeterX_SDK"}],"navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"roleHeading":"Enumeration","externalID":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType","title":"PXPolicyUrlRequestInterceptionType"},"abstract":[{"type":"text","text":"The URL request interception type."}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH","doc:\/\/com.perimeterx.mobile-sdk\/SY"],"title":"Conforms To","kind":"relationships"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","interfaceLanguage":"swift"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/interceptAndRetryRequest":{"type":"topic","abstract":[{"type":"text","text":"Same as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptWithDelayedResponse"},{"text":". When the user solves the challenge, the SDK will send the original request again.","type":"text"}],"title":"PXPolicyUrlRequestInterceptionType.interceptAndRetryRequest","role":"symbol","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptAndRetryRequest","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interceptAndRetryRequest"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/interceptandretryrequest","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/SY":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"kind":"symbol","role":"collection","type":"topic","title":"PerimeterX_SDK","abstract":[],"url":"\/documentation\/perimeterx_sdk","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/init(rawValue:)":{"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/init(rawValue:)","type":"topic","title":"init(rawValue:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/rawrepresentable-implementations"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/interceptWithDelayedResponse":{"type":"topic","abstract":[{"type":"text","text":"Same as "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","isActive":true,"type":"reference"},{"text":". The SDK delays the error response to your app until the user solve or cancel the challenge.","type":"text"}],"title":"PXPolicyUrlRequestInterceptionType.interceptWithDelayedResponse","role":"symbol","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptWithDelayedResponse","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptWithDelayedResponse","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/interceptwithdelayedresponse","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/Equatable-Implementations":{"kind":"article","abstract":[],"role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/Equatable-Implementations"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/none":{"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"role":"symbol","title":"PXPolicyUrlRequestInterceptionType.none","kind":"symbol","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeNone","kind":"identifier"}],"abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/intercept":{"abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"type":"text","text":" "},{"text":"The SDK can intercept those types of requests:","type":"text"}],"title":"PXPolicyUrlRequestInterceptionType.intercept","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intercept"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","role":"symbol","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/intercept","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType":{"role":"symbol","abstract":[{"type":"text","text":"The URL request interception type."}],"title":"PXPolicyUrlRequestInterceptionType","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"PXPolicyUrlRequestInterceptionType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptAndRetryRequest","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptWithDelayedResponse","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1interceptAndRetryRequest\/title","value":"PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest","op":"replace"},{"value":[{"text":"PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1interceptAndRetryRequest\/fragments"},{"value":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1interceptWithDelayedResponse\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1interceptWithDelayedResponse\/fragments","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/title","value":"PXPolicyUrlRequestInterceptionTypeNone"},{"op":"replace","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/fragments"},{"op":"replace","value":"PXPolicyUrlRequestInterceptionTypeIntercept","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/fragments","op":"replace","value":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}]},{"value":"PXPolicyUrlRequestInterceptionType","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/title"},{"value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}