{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PXPolicy"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","title":"PXPolicy","symbolKind":"class","role":"symbol","modules":[{"name":"PerimeterX_SDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PXPolicy"}],"navigatorTitle":[{"kind":"identifier","text":"PXPolicy"}],"roleHeading":"Class"},"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowDeviceMotionDetection","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowJavaScriptEvaluation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowTouchDetection","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/byPassMonitorHeaderValue","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/doctorCheckEnabled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/hybridAppSupportEnabled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/copy(with:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/set(domains:forAppId:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorDelegateQueue","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorUrlSessionConfiguration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorUrlSessionDelegate"]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP","doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP","doc:\/\/com.perimeterx.mobile-sdk\/SQ","doc:\/\/com.perimeterx.mobile-sdk\/SH"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicy"]},{"paths":["\/documentation\/perimeterx_sdk\/pxpolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/doctorCheckEnabled":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Set this property to "},{"type":"codeVoice","code":"true"},{"text":" to enable the ","type":"text"},{"code":"Doctor App","type":"codeVoice"},{"type":"text","text":" - a tool to verify the integration of the SDK in your app. Make sure to set this property to "},{"code":"false","type":"codeVoice"},{"type":"text","text":" before deploying you app to production. Default is "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"title":"doctorCheckEnabled","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/doctorcheckenabled","navigatorTitle":[{"kind":"identifier","text":"doctorCheckEnabled"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/doctorCheckEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctorCheckEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.perimeterx.mobile-sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SH","title":"Swift.Hashable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/copy(with:)":{"kind":"symbol","title":"copy(with:)","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/copy(with:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copy"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"keyword","text":"Any"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/copy(with:)","type":"topic"},"doc://com.perimeterx.mobile-sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/automaticInterceptorDelegateQueue":{"role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"OperationQueue"},{"text":" that should be used by the SDK.","type":"text"}],"title":"automaticInterceptorDelegateQueue","navigatorTitle":[{"text":"automaticInterceptorDelegateQueue","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorDelegateQueue","type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptordelegatequeue","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"automaticInterceptorDelegateQueue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"OperationQueue"},{"kind":"text","text":"?"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/hybridAppSupportEnabled":{"kind":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/hybridappsupportenabled","title":"hybridAppSupportEnabled","abstract":[{"type":"text","text":"This property is relevant only for apps that use "},{"type":"codeVoice","code":"WKWebView"},{"text":" to load their website (which also protected by PerimeterX). By setting this property to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":", the SDK syncs both the native and the web sessions to ensure flawless experience. Default is "},{"type":"codeVoice","code":"false"},{"text":". You must set your domains with the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/set(domains:forAppId:)","type":"reference"},{"type":"text","text":" function to ensure the hybrid app support is working as expected."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hybridAppSupportEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/hybridAppSupportEnabled","navigatorTitle":[{"text":"hybridAppSupportEnabled","kind":"identifier"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s7CVarArgP"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/allowTouchDetection":{"navigatorTitle":[{"kind":"identifier","text":"allowTouchDetection"}],"abstract":[{"type":"text","text":"Allow the SDK to intercept touches on the screen. Default is "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowTouchDetection","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowTouchDetection","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"allowTouchDetection","type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/allowtouchdetection","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/s23CustomStringConvertibleP"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/automaticInterceptorUrlSessionConfiguration":{"kind":"symbol","title":"automaticInterceptorUrlSessionConfiguration","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptorurlsessionconfiguration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URLSessionConfiguration"},{"text":" that should be used by the SDK. Default is ","type":"text"},{"code":"URLSessionConfiguration.default","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automaticInterceptorUrlSessionConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"}],"navigatorTitle":[{"text":"automaticInterceptorUrlSessionConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorUrlSessionConfiguration","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/intercept":{"abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"text":" ","type":"text"},{"text":"The SDK can intercept those types of requests:","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/intercept","title":"PXPolicyUrlRequestInterceptionType.intercept","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"intercept","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/byPassMonitorHeaderValue":{"role":"symbol","title":"byPassMonitorHeaderValue","kind":"symbol","type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/bypassmonitorheadervalue","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/byPassMonitorHeaderValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"byPassMonitorHeaderValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/allowDeviceMotionDetection":{"kind":"symbol","title":"allowDeviceMotionDetection","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/allowdevicemotiondetection","abstract":[{"text":"Allow the SDK to collect device motion data. This feature is disabled when ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowTouchDetection","isActive":true},{"text":" is ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":". The SDK is creating an instance of "},{"code":"CMMotionManager","type":"codeVoice"},{"type":"text","text":" to monitor device’s motion. However, it’s not recommended to have more than one instance in the app. By setting this property to "},{"code":"false","type":"codeVoice"},{"text":", the SDK won’t create an instance of ","type":"text"},{"code":"CMMotionManager","type":"codeVoice"},{"text":". Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowDeviceMotionDetection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"allowDeviceMotionDetection"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowDeviceMotionDetection","type":"topic"},"doc://com.perimeterx.mobile-sdk/SQ":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/set(domains:forAppId:)":{"kind":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/set(domains:forappid:)","title":"set(domains:forAppId:)","abstract":[{"type":"text","text":"Use this function to register domains which your app interact with. The SDK (when the "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType","isActive":true},{"type":"text","text":" is set to any value rather than "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none"},{"type":"text","text":") is intercepting URL requests to those domains only. If you do not set domain, the SDK will intercept all URL requests. In addition, the SDK (when "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/hybridAppSupportEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":") is setting cookies in your web views in order to sync between the native and the web sessions. However, the SDK will set cookies only for domains that are set in this property. Therefore, you must set your domains to enable hybrid app support. Example: for the website ","type":"text"},{"type":"codeVoice","code":"www.google.com"},{"type":"text","text":" you should set the domain: "},{"code":"google.com","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"text":"(","kind":"text"},{"text":"domains","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/set(domains:forAppId:)","navigatorTitle":[{"kind":"identifier","text":"setWithDomains:forAppId:"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/objc(pl)NSCopying":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"url":"\/documentation\/perimeterx_sdk","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","abstract":[],"type":"topic","title":"PerimeterX_SDK"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/allowJavaScriptEvaluation":{"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/allowjavascriptevaluation","type":"topic","title":"allowJavaScriptEvaluation","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowJavaScriptEvaluation","role":"symbol","abstract":[{"text":"Allow the SDK to evaluate JavaScript code in your web views (for hybrid app support). You should disable JavaScript code when using ApplePay in your web view. When you disable JavaScript evaluation, the SDK could store cookies instead (depending on the run time environment). Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowJavaScriptEvaluation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"allowJavaScriptEvaluation"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","abstract":[{"text":"The policy that define the behaviour of the SDK.","type":"text"}],"title":"PXPolicy","url":"\/documentation\/perimeterx_sdk\/pxpolicy","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PXPolicy","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"PXPolicy","kind":"identifier"}],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/urlRequestInterceptionType":{"type":"topic","kind":"symbol","abstract":[{"text":"Decide how the SDK should handle URL requests. Default is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType","title":"urlRequestInterceptionType","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"urlRequestInterceptionType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType","text":"PXPolicyUrlRequestInterceptionType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"urlRequestInterceptionType"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicy\/urlrequestinterceptiontype"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/init","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/init"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/automaticInterceptorUrlSessionDelegate":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorUrlSessionDelegate","title":"automaticInterceptorUrlSessionDelegate","type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"URLSessionDelegate","type":"codeVoice"},{"type":"text","text":" that should be used by the SDK. Default is "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" (the SDK will be the delegate). The SDK implements "},{"type":"codeVoice","code":"willPerformHTTPRedirection"},{"type":"text","text":" and "},{"code":"needNewBodyStream","type":"codeVoice"},{"text":" function in the ","type":"text"},{"type":"codeVoice","code":"URLSessionDelegate"},{"text":". However, if your ","type":"text"},{"code":"URLSessionDelegate","type":"codeVoice"},{"type":"text","text":" implements other functions, like "},{"code":"didReceiveChallenge","type":"codeVoice"},{"text":", then you should provide your own delegate.","type":"text"}],"navigatorTitle":[{"text":"automaticInterceptorUrlSessionDelegate","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"automaticInterceptorUrlSessionDelegate","kind":"identifier"},{"kind":"text","text":": "},{"text":"URLSessionDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSURLSessionDelegate"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/automaticinterceptorurlsessiondelegate"},"doc://com.perimeterx.mobile-sdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/none":{"abstract":[{"text":"The SDK does not intercept URL requests at all.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}],"title":"PXPolicyUrlRequestInterceptionType.none","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"PXPolicy"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PXPolicy"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PXPolicy"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowDeviceMotionDetection","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowJavaScriptEvaluation","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/allowTouchDetection","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/doctorCheckEnabled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/hybridAppSupportEnabled","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/copy(with:)","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/init","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/set(domains:forAppId:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorDelegateQueue","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorUrlSessionConfiguration","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/automaticInterceptorUrlSessionDelegate"]}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/objc(pl)NSCopying"],"title":"Conforms To","type":"conformsTo"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PXPolicy"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"doctorCheckEnabled","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1doctorCheckEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1doctorCheckEnabled\/fragments","value":[{"text":"doctorCheckEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1copy(with:)\/title","value":"copyWithZone:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1copy(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorDelegateQueue\/title","value":"automaticInterceptorDelegateQueue"},{"value":[{"text":"automaticInterceptorDelegateQueue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorDelegateQueue\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1hybridAppSupportEnabled\/title","op":"replace","value":"hybridAppSupportEnabled"},{"value":[{"kind":"identifier","text":"hybridAppSupportEnabled"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1hybridAppSupportEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1allowTouchDetection\/title","value":"allowTouchDetection"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1allowTouchDetection\/fragments","value":[{"kind":"identifier","text":"allowTouchDetection"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorUrlSessionConfiguration\/title","op":"replace","value":"automaticInterceptorUrlSessionConfiguration"},{"value":[{"text":"automaticInterceptorUrlSessionConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorUrlSessionConfiguration\/fragments","op":"replace"},{"value":"PXPolicyUrlRequestInterceptionTypeIntercept","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/fragments","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeIntercept"}]},{"value":"allowDeviceMotionDetection","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1allowDeviceMotionDetection\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1allowDeviceMotionDetection\/fragments","value":[{"kind":"identifier","text":"allowDeviceMotionDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1set(domains:forAppId:)\/title","value":"setWithDomains:forAppId:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1set(domains:forAppId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setWithDomains:forAppId:"}],"op":"replace"},{"value":"allowJavaScriptEvaluation","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1allowJavaScriptEvaluation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1allowJavaScriptEvaluation\/fragments","value":[{"kind":"identifier","text":"allowJavaScriptEvaluation"}]},{"value":"PXPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PXPolicy"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments"},{"value":"urlRequestInterceptionType","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1urlRequestInterceptionType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1urlRequestInterceptionType\/fragments","value":[{"text":"urlRequestInterceptionType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorUrlSessionDelegate\/title","value":"automaticInterceptorUrlSessionDelegate"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1automaticInterceptorUrlSessionDelegate\/fragments","value":[{"kind":"identifier","text":"automaticInterceptorUrlSessionDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/title","op":"replace","value":"PXPolicyUrlRequestInterceptionTypeNone"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/fragments","op":"replace","value":[{"text":"PXPolicyUrlRequestInterceptionTypeNone","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}