{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Challenge was solved by the user.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeSolved"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"challengeSolved"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/challengesolved"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/challengesolved"]}],"sections":[],"metadata":{"symbolKind":"case","externalID":"c:@M@PerimeterX_SDK@E@PerimeterXErrorCode@PerimeterXErrorCodeChallengeSolved","title":"PerimeterXErrorCode.challengeSolved","roleHeading":"Case","modules":[{"name":"PerimeterX_SDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"challengeSolved","kind":"identifier"}],"navigatorTitle":[{"text":"PerimeterXErrorCodeChallengeSolved","kind":"identifier"}]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","title":"PerimeterX_SDK","kind":"symbol","abstract":[],"url":"\/documentation\/perimeterx_sdk","type":"topic","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode":{"title":"PerimeterXErrorCode","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterXErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCode"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","abstract":[{"text":"SDK’s error codes. This will be included in errors objects that generated by the SDK.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/challengeSolved":{"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/challengesolved","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeSolved","title":"PerimeterXErrorCode.challengeSolved","navigatorTitle":[{"text":"PerimeterXErrorCodeChallengeSolved","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Challenge was solved by the user.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"challengeSolved","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"PerimeterXErrorCodeChallengeSolved","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"PerimeterXErrorCodeChallengeSolved"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PerimeterXErrorCodeChallengeSolved","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"PerimeterXErrorCode","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PerimeterXErrorCode"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/fragments"},{"op":"replace","value":[{"text":"PerimeterXErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/navigatorTitle"},{"op":"replace","value":"PerimeterXErrorCodeChallengeSolved","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeSolved\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PerimeterXErrorCodeChallengeSolved"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeSolved\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}