{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"httpBodyInputStreamReadFailed","kind":"identifier"}]}]}],"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpBodyInputStreamReadFailed"}],"roleHeading":"Case","navigatorTitle":[{"text":"PerimeterXErrorCodeHttpBodyInputStreamReadFailed","kind":"identifier"}],"title":"PerimeterXErrorCode.httpBodyInputStreamReadFailed","modules":[{"name":"PerimeterX_SDK"}],"symbolKind":"case","externalID":"c:@M@PerimeterX_SDK@E@PerimeterXErrorCode@PerimeterXErrorCodeHttpBodyInputStreamReadFailed"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode"]]},"kind":"symbol","abstract":[{"text":"Failed to read body from input stream of the request.","type":"text"}],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/httpbodyinputstreamreadfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/httpbodyinputstreamreadfailed"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/httpBodyInputStreamReadFailed"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode":{"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterXErrorCode"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCode"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","title":"PerimeterXErrorCode","abstract":[{"text":"SDK’s error codes. This will be included in errors objects that generated by the SDK.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/httpBodyInputStreamReadFailed":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"httpBodyInputStreamReadFailed","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/httpBodyInputStreamReadFailed","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCodeHttpBodyInputStreamReadFailed"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/httpbodyinputstreamreadfailed","title":"PerimeterXErrorCode.httpBodyInputStreamReadFailed","abstract":[{"text":"Failed to read body from input stream of the request.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"title":"PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk","role":"collection","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PerimeterXErrorCodeHttpBodyInputStreamReadFailed","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PerimeterXErrorCodeHttpBodyInputStreamReadFailed","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"PerimeterXErrorCodeHttpBodyInputStreamReadFailed","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/title","value":"PerimeterXErrorCode"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/fragments","op":"replace","value":[{"text":"PerimeterXErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1httpBodyInputStreamReadFailed\/title","value":"PerimeterXErrorCodeHttpBodyInputStreamReadFailed","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1httpBodyInputStreamReadFailed\/fragments","value":[{"kind":"identifier","text":"PerimeterXErrorCodeHttpBodyInputStreamReadFailed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}