{"metadata":{"symbolKind":"case","title":"PerimeterXErrorCode.internalError","role":"symbol","modules":[{"name":"PerimeterX_SDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"navigatorTitle":[{"text":"PerimeterXErrorCodeInternalError","kind":"identifier"}],"externalID":"c:@M@PerimeterX_SDK@E@PerimeterXErrorCode@PerimeterXErrorCodeInternalError","roleHeading":"Case"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode"]]},"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/internalerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/internalerror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/internalError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Internal error in the SDK."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"type":"topic","url":"\/documentation\/perimeterx_sdk","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"title":"PerimeterX_SDK","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode":{"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode","kind":"symbol","navigatorTitle":[{"text":"PerimeterXErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerimeterXErrorCode","kind":"identifier"}],"type":"topic","title":"PerimeterXErrorCode","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/internalError":{"type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCodeInternalError","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}],"title":"PerimeterXErrorCode.internalError","role":"symbol","abstract":[{"type":"text","text":"Internal error in the SDK."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/internalError","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/internalerror","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PerimeterXErrorCodeInternalError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PerimeterXErrorCodeInternalError"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"PerimeterXErrorCodeInternalError","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"PerimeterXErrorCode","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/title"},{"value":[{"text":"PerimeterXErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1internalError\/title","value":"PerimeterXErrorCodeInternalError","op":"replace"},{"value":[{"kind":"identifier","text":"PerimeterXErrorCodeInternalError"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1internalError\/fragments"}]}]}