{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"missingAppId"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/missingappid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/missingappid"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode"]]},"metadata":{"modules":[{"name":"PerimeterX_SDK"}],"roleHeading":"Case","title":"PerimeterXErrorCode.missingAppId","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"missingAppId"}],"navigatorTitle":[{"text":"PerimeterXErrorCodeMissingAppId","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@PerimeterX_SDK@E@PerimeterXErrorCode@PerimeterXErrorCodeMissingAppId","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/missingAppId"},"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)"},{"type":"text","text":" or "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","isActive":true},{"type":"text","text":" functions were called without any AppID."}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/missingAppId":{"title":"PerimeterXErrorCode.missingAppId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCodeMissingAppId"}],"type":"topic","abstract":[{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","isActive":true},{"type":"text","text":" or "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)"},{"text":" functions were called without any AppID.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/missingAppId","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"missingAppId","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/missingappid"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appIds:delegate:policy:)":{"navigatorTitle":[{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}],"title":"start(appIds:delegate:policy:)","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appids:delegate:policy:)","abstract":[{"type":"text","text":"Start the SDK."}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"(","kind":"text"},{"text":"appIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"text":"PerimeterXDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"policy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","text":"PXPolicy","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode":{"navigatorTitle":[{"text":"PerimeterXErrorCode","kind":"identifier"}],"title":"PerimeterXErrorCode","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterXErrorCode"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"title":"PerimeterX_SDK","kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"role":"collection","url":"\/documentation\/perimeterx_sdk"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:policy:)":{"role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:policy:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PerimeterXDelegate","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"text":"PXPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"start(appId:delegate:policy:)","abstract":[{"text":"Start the SDK.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PerimeterXErrorCodeMissingAppId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PerimeterXErrorCodeMissingAppId"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"PerimeterXErrorCodeMissingAppId","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PerimeterXErrorCodeMissingAppId","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1missingAppId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PerimeterXErrorCodeMissingAppId"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1missingAppId\/fragments"},{"value":"startWithAppIds:delegate:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appIds:delegate:policy:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appIds:delegate:policy:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}],"op":"replace"},{"value":"PerimeterXErrorCode","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/fragments","value":[{"text":"PerimeterXErrorCode","kind":"identifier"}]},{"value":"startWithAppId:delegate:policy:error:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"startWithAppId:delegate:policy:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}