{"metadata":{"title":"PerimeterXErrorCode.requestWasBlocked","symbolKind":"case","modules":[{"name":"PerimeterX_SDK"}],"role":"symbol","externalID":"c:@M@PerimeterX_SDK@E@PerimeterXErrorCode@PerimeterXErrorCodeRequestWasBlocked","navigatorTitle":[{"text":"PerimeterXErrorCodeRequestWasBlocked","kind":"identifier"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"requestWasBlocked","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/requestWasBlocked"},"abstract":[{"text":"URL request was blocked by PerimeterX.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestWasBlocked","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/requestwasblocked"]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/requestwasblocked"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"kind":"symbol","abstract":[],"role":"collection","title":"PerimeterX_SDK","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/requestWasBlocked":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/requestWasBlocked","abstract":[{"type":"text","text":"URL request was blocked by PerimeterX."}],"title":"PerimeterXErrorCode.requestWasBlocked","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestWasBlocked"}],"kind":"symbol","navigatorTitle":[{"text":"PerimeterXErrorCodeRequestWasBlocked","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/requestwasblocked"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCode"}],"role":"symbol","title":"PerimeterXErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerimeterXErrorCode","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode","type":"topic","kind":"symbol","abstract":[{"text":"SDK’s error codes. This will be included in errors objects that generated by the SDK.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"PerimeterXErrorCodeRequestWasBlocked","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PerimeterXErrorCodeRequestWasBlocked","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PerimeterXErrorCodeRequestWasBlocked","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1requestWasBlocked\/title","value":"PerimeterXErrorCodeRequestWasBlocked"},{"value":[{"kind":"identifier","text":"PerimeterXErrorCodeRequestWasBlocked"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1requestWasBlocked\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/title","value":"PerimeterXErrorCode"},{"op":"replace","value":[{"text":"PerimeterXErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}