{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startWasNotCalled"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/startwasnotcalled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/startwasnotcalled"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"startWasNotCalled","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"The SDK failed to perform the operation. Make sure to call the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)"},{"type":"text","text":" function."}],"metadata":{"title":"PerimeterXErrorCode.startWasNotCalled","externalID":"c:@M@PerimeterX_SDK@E@PerimeterXErrorCode@PerimeterXErrorCodeStartWasNotCalled","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startWasNotCalled"}],"roleHeading":"Case","navigatorTitle":[{"text":"PerimeterXErrorCodeStartWasNotCalled","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"PerimeterX_SDK"}]},"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:policy:)":{"type":"topic","title":"start(appId:delegate:policy:)","abstract":[{"type":"text","text":"Start the SDK."}],"role":"symbol","navigatorTitle":[{"text":"startWithAppId:delegate:policy:error:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PerimeterXDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},{"kind":"text","text":"?, "},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PXPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:policy:)","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/startWasNotCalled":{"title":"PerimeterXErrorCode.startWasNotCalled","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"startWasNotCalled","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startWasNotCalled","type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCodeStartWasNotCalled","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/startwasnotcalled","role":"symbol","abstract":[{"type":"text","text":"The SDK failed to perform the operation. Make sure to call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","isActive":true,"type":"reference"},{"text":" function.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"kind":"symbol","role":"collection","type":"topic","title":"PerimeterX_SDK","abstract":[],"url":"\/documentation\/perimeterx_sdk","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode":{"navigatorTitle":[{"text":"PerimeterXErrorCode","kind":"identifier"}],"title":"PerimeterXErrorCode","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PerimeterXErrorCode","kind":"identifier"}],"type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode","abstract":[{"text":"SDK’s error codes. This will be included in errors objects that generated by the SDK.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"PerimeterXErrorCodeStartWasNotCalled","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PerimeterXErrorCodeStartWasNotCalled"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PerimeterXErrorCodeStartWasNotCalled","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/title","value":"startWithAppId:delegate:policy:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"startWithAppId:delegate:policy:error:","kind":"identifier"}]},{"op":"replace","value":"PerimeterXErrorCodeStartWasNotCalled","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1startWasNotCalled\/title"},{"value":[{"text":"PerimeterXErrorCodeStartWasNotCalled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1startWasNotCalled\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/title","op":"replace","value":"PerimeterXErrorCode"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"PerimeterXErrorCode"}]}]}]}