{"kind":"symbol","metadata":{"title":"PerimeterXErrorCode.startCalledMoreThanOnce","navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCodeStartCalledMoreThanOnce"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCalledMoreThanOnce"}],"symbolKind":"case","externalID":"c:@M@PerimeterX_SDK@E@PerimeterXErrorCode@PerimeterXErrorCodeStartCalledMoreThanOnce","modules":[{"name":"PerimeterX_SDK"}],"roleHeading":"Case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCalledMoreThanOnce"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/startcalledmorethanonce"]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/startcalledmorethanonce"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startCalledMoreThanOnce","interfaceLanguage":"swift"},"abstract":[{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","type":"reference","isActive":true},{"text":" or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)"},{"text":" functions were called more than once.","type":"text"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:policy:)":{"url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:policy:)","title":"start(appId:delegate:policy:)","abstract":[{"text":"Start the SDK.","type":"text"}],"navigatorTitle":[{"text":"startWithAppId:delegate:policy:error:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PerimeterXDelegate","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"text":"PXPolicy","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk","title":"PerimeterX_SDK","type":"topic","role":"collection","abstract":[],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appIds:delegate:policy:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","title":"start(appIds:delegate:policy:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appIds"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate","kind":"typeIdentifier","text":"PerimeterXDelegate"},{"kind":"text","text":"?, "},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PXPolicy","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Start the SDK.","type":"text"}],"type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appids:delegate:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/startCalledMoreThanOnce":{"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/startcalledmorethanonce","title":"PerimeterXErrorCode.startCalledMoreThanOnce","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)"},{"text":" or ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","isActive":true},{"text":" functions were called more than once.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCodeStartCalledMoreThanOnce"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCalledMoreThanOnce"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/startCalledMoreThanOnce","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode":{"url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode","type":"topic","navigatorTitle":[{"text":"PerimeterXErrorCode","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerimeterXErrorCode"}],"abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","title":"PerimeterXErrorCode"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PerimeterXErrorCodeStartCalledMoreThanOnce"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"PerimeterXErrorCodeStartCalledMoreThanOnce","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"PerimeterXErrorCodeStartCalledMoreThanOnce","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"startWithAppId:delegate:policy:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"startWithAppId:delegate:policy:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/fragments","op":"replace"},{"value":"startWithAppIds:delegate:policy:error:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appIds:delegate:policy:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appIds:delegate:policy:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startWithAppIds:delegate:policy:error:"}]},{"value":"PerimeterXErrorCodeStartCalledMoreThanOnce","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1startCalledMoreThanOnce\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1startCalledMoreThanOnce\/fragments","value":[{"text":"PerimeterXErrorCodeStartCalledMoreThanOnce","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/title","value":"PerimeterXErrorCode"},{"op":"replace","value":[{"text":"PerimeterXErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}