{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"tokenWasNotGenerated","kind":"identifier"}],"modules":[{"name":"PerimeterX_SDK"}],"roleHeading":"Case","title":"PerimeterXErrorCode.tokenWasNotGenerated","role":"symbol","symbolKind":"case","externalID":"c:@M@PerimeterX_SDK@E@PerimeterXErrorCode@PerimeterXErrorCodeTokenWasNotGenerated","navigatorTitle":[{"text":"PerimeterXErrorCodeTokenWasNotGenerated","kind":"identifier"}]},"abstract":[{"text":"The SDK failed to generate token. Make sure the AppID is set correctly.","type":"text"}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenWasNotGenerated"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/tokenWasNotGenerated"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/tokenwasnotgenerated"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/tokenwasnotgenerated"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PerimeterXErrorCode","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","title":"PerimeterXErrorCode","type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode","abstract":[{"type":"text","text":"SDK’s error codes. This will be included in errors objects that generated by the SDK."}],"navigatorTitle":[{"text":"PerimeterXErrorCode","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/tokenWasNotGenerated":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/tokenWasNotGenerated","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tokenWasNotGenerated"}],"type":"topic","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/tokenwasnotgenerated","title":"PerimeterXErrorCode.tokenWasNotGenerated","abstract":[{"text":"The SDK failed to generate token. Make sure the AppID is set correctly.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PerimeterXErrorCodeTokenWasNotGenerated"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"kind":"symbol","type":"topic","abstract":[],"title":"PerimeterX_SDK","role":"collection","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PerimeterXErrorCodeTokenWasNotGenerated","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"PerimeterXErrorCodeTokenWasNotGenerated","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"PerimeterXErrorCodeTokenWasNotGenerated","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/title","value":"PerimeterXErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode\/fragments","value":[{"kind":"identifier","text":"PerimeterXErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1tokenWasNotGenerated\/title","value":"PerimeterXErrorCodeTokenWasNotGenerated"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1tokenWasNotGenerated\/fragments","value":[{"kind":"identifier","text":"PerimeterXErrorCodeTokenWasNotGenerated"}]}]}]}