{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType"]]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptAndRetryRequest","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Same as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptWithDelayedResponse"},{"text":". When the user solves the challenge, the SDK will send the original request again.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/interceptandretryrequest"]},{"paths":["\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/interceptandretryrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"interceptAndRetryRequest","kind":"identifier"}],"navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest","kind":"identifier"}],"externalID":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType@PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest","title":"PXPolicyUrlRequestInterceptionType.interceptAndRetryRequest","modules":[{"name":"PerimeterX_SDK"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interceptAndRetryRequest"}]}],"kind":"declarations"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/intercept":{"title":"PXPolicyUrlRequestInterceptionType.intercept","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}],"kind":"symbol","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/intercept","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"intercept"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"type":"topic","title":"PXPolicyUrlRequestInterceptionType","role":"symbol","abstract":[{"text":"The URL request interception type.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","url":"\/documentation\/perimeterx_sdk","title":"PerimeterX_SDK","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/interceptAndRetryRequest":{"abstract":[{"text":"Same as ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptWithDelayedResponse"},{"type":"text","text":". When the user solves the challenge, the SDK will send the original request again."}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptAndRetryRequest","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interceptAndRetryRequest"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/interceptandretryrequest","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest","kind":"identifier"}],"title":"PXPolicyUrlRequestInterceptionType.interceptAndRetryRequest","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/interceptWithDelayedResponse":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptWithDelayedResponse","kind":"symbol","type":"topic","title":"PXPolicyUrlRequestInterceptionType.interceptWithDelayedResponse","abstract":[{"type":"text","text":"Same as "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","type":"reference","isActive":true},{"type":"text","text":". The SDK delays the error response to your app until the user solve or cancel the challenge."}],"role":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/interceptwithdelayedresponse","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"interceptWithDelayedResponse"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/title","value":"PXPolicyUrlRequestInterceptionTypeIntercept"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/fragments","op":"replace","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeIntercept"}]},{"op":"replace","value":"PXPolicyUrlRequestInterceptionType","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/fragments","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}]},{"value":"PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1interceptAndRetryRequest\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1interceptAndRetryRequest\/fragments","value":[{"text":"PXPolicyUrlRequestInterceptionTypeInterceptAndRetryRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1interceptWithDelayedResponse\/title","value":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1interceptWithDelayedResponse\/fragments","op":"replace","value":[{"text":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}