{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intercept"}],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"URLSession."}]}]},{"content":[{"inlineContent":[{"text":"WKWebView.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Any 3rd party library which based on URLSession (like Alamofire).","type":"text"},{"text":" ","type":"text"},{"text":"Notice that the SDK cannot intercept requests from SFSafariViewController.","type":"text"}]}]}],"type":"orderedList"}],"kind":"content"}],"metadata":{"modules":[{"name":"PerimeterX_SDK"}],"roleHeading":"Case","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}],"externalID":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType@PXPolicyUrlRequestInterceptionTypeIntercept","role":"symbol","title":"PXPolicyUrlRequestInterceptionType.intercept","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"intercept","kind":"identifier"}],"symbolKind":"case"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept"},"abstract":[{"text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The SDK can intercept those types of requests:"}],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/intercept"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/intercept"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/intercept":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"intercept","kind":"identifier"}],"abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"text":" ","type":"text"},{"type":"text","text":"The SDK can intercept those types of requests:"}],"role":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/intercept","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeIntercept"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","kind":"symbol","title":"PXPolicyUrlRequestInterceptionType.intercept","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"title":"PXPolicyUrlRequestInterceptionType","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","kind":"symbol","abstract":[{"text":"The URL request interception type.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"role":"collection","title":"PerimeterX_SDK","kind":"symbol","url":"\/documentation\/perimeterx_sdk","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PXPolicyUrlRequestInterceptionTypeIntercept","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"PXPolicyUrlRequestInterceptionTypeIntercept","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/title"},{"value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeIntercept"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/fragments","op":"replace"},{"value":"PXPolicyUrlRequestInterceptionType","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/fragments","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}]}]}]}