{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType"]]},"metadata":{"externalID":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType@PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse","modules":[{"name":"PerimeterX_SDK"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"interceptWithDelayedResponse","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse"}],"role":"symbol","title":"PXPolicyUrlRequestInterceptionType.interceptWithDelayedResponse"},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptWithDelayedResponse","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/interceptwithdelayedresponse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/interceptwithdelayedresponse"]}],"abstract":[{"text":"Same as ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept"},{"text":". The SDK delays the error response to your app until the user solve or cancel the challenge.","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interceptWithDelayedResponse","kind":"identifier"}]}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/interceptWithDelayedResponse":{"title":"PXPolicyUrlRequestInterceptionType.interceptWithDelayedResponse","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/interceptWithDelayedResponse","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"interceptWithDelayedResponse","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/interceptwithdelayedresponse","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse","kind":"identifier"}],"abstract":[{"type":"text","text":"Same as "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept"},{"type":"text","text":". The SDK delays the error response to your app until the user solve or cancel the challenge."}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/intercept":{"abstract":[{"type":"text","text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses."},{"text":" ","type":"text"},{"text":"The SDK can intercept those types of requests:","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/intercept","title":"PXPolicyUrlRequestInterceptionType.intercept","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"intercept","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"url":"\/documentation\/perimeterx_sdk","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","abstract":[],"type":"topic","title":"PerimeterX_SDK"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType":{"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"abstract":[{"type":"text","text":"The URL request interception type."}],"title":"PXPolicyUrlRequestInterceptionType","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","type":"topic","kind":"symbol","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1interceptWithDelayedResponse\/title","value":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse","op":"replace"},{"value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeInterceptWithDelayedResponse"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1interceptWithDelayedResponse\/fragments"},{"value":"PXPolicyUrlRequestInterceptionTypeIntercept","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/fragments","op":"replace","value":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/title","value":"PXPolicyUrlRequestInterceptionType","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/fragments","op":"replace","value":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}