{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}],"title":"PXPolicyUrlRequestInterceptionType.none","externalID":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType@PXPolicyUrlRequestInterceptionTypeNone","modules":[{"name":"PerimeterX_SDK"}],"roleHeading":"Case","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none"]},{"paths":["\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/none":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","kind":"symbol","title":"PXPolicyUrlRequestInterceptionType.none","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"title":"PXPolicyUrlRequestInterceptionType","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","kind":"symbol","abstract":[{"text":"The URL request interception type.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"role":"collection","title":"PerimeterX_SDK","kind":"symbol","url":"\/documentation\/perimeterx_sdk","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PXPolicyUrlRequestInterceptionTypeNone","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"PXPolicyUrlRequestInterceptionTypeNone","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/title","value":"PXPolicyUrlRequestInterceptionTypeNone"},{"op":"replace","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/fragments"},{"value":"PXPolicyUrlRequestInterceptionType","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/fragments"}]}]}