{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandleResponse"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier","text":"URLResponse"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The response that was received from the URL request."}]}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The data that was received from the URL request."}]}]},{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"text":"The AppID of your account. Ignore this param if you use only one AppID.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"text":" if the PerimeterX’s payload in the response can be handled by the SDK. This function does not present the block screen.","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/canhandleresponse(response:data:forappid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/canhandleresponse(response:data:forappid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)canHandleResponseWithResponse:data:forAppId:","roleHeading":"Type Method","navigatorTitle":[{"text":"canHandleResponseWithResponse:data:forAppId:","kind":"identifier"}],"modules":[{"name":"PerimeterX_SDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canHandleResponse"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"canHandleResponse(response:data:forAppId:)","role":"symbol"},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/canHandleResponse(response:data:forAppId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function checks if the SDK can handle the URL request’s response and presents the block screen."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"navigatorTitle":[{"text":"PerimeterX","kind":"identifier"}],"abstract":[{"type":"text","text":"PerimeterX main class. You should interact with it in order to setup and start the SDK."}],"url":"\/documentation\/perimeterx_sdk\/perimeterx","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterX"}],"title":"PerimeterX","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/canHandleResponse(response:data:forAppId:)":{"navigatorTitle":[{"kind":"identifier","text":"canHandleResponseWithResponse:data:forAppId:"}],"abstract":[{"type":"text","text":"This function checks if the SDK can handle the URL request’s response and presents the block screen."}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/canhandleresponse(response:data:forappid:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"canHandleResponse","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier","text":"URLResponse"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"canHandleResponse(response:data:forAppId:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/canHandleResponse(response:data:forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"title":"PerimeterX_SDK","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","url":"\/documentation\/perimeterx_sdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"canHandleResponseWithResponse:data:forAppId:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"canHandleResponseWithResponse:data:forAppId:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"canHandleResponseWithResponse:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLResponse","text":"NSURLResponse","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"response","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"data:"},{"kind":"text","text":"("},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forAppId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","value":"PerimeterX"},{"value":[{"kind":"identifier","text":"PerimeterX"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments"},{"value":"canHandleResponseWithResponse:data:forAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1canHandleResponse(response:data:forAppId:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"canHandleResponseWithResponse:data:forAppId:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1canHandleResponse(response:data:forAppId:)\/fragments"}]}]}