{"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/canHandleResponse(forAppId:data:response:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"metadata":{"title":"canHandleResponse(forAppId:data:response:)","role":"symbol","externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)canHandleResponseForAppId:data:response:","roleHeading":"Type Method","modules":[{"name":"PerimeterX_SDK"}],"navigatorTitle":[{"text":"canHandleResponseForAppId:data:response:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canHandleResponse"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/canhandleresponse(forappid:data:response:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/canhandleresponse(forappid:data:response:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"This function checks if the SDK can handle the URL request’s response and presents the block screen.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"canHandleResponse","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":", ","kind":"text"},{"text":"response","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"text":"The AppID of your account. Ignore this param if you use only one AppID.","type":"text"}]}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"text":"The data that was received from the URL request.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The response that was received from the URL request."}],"type":"paragraph"}],"name":"response"}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Returns true if the PerimeterX’s payload in the response can be handled by the SDK. This function does not present the block screen. This function should be used only when the ","type":"text"},{"type":"codeVoice","code":"PXPolicy\/requestsInterceptedAutomaticallyEnabled"},{"text":" is set to false in the policy.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You must call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)","type":"reference","isActive":true},{"text":" function and wait until it’s done before calling this function.","type":"text"}]}],"kind":"content"}],"sections":[],"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:enableDoctorCheck:completion:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate","text":"PerimeterXDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"enableDoctorCheck"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())"}],"title":"start(appId:delegate:enableDoctorCheck:completion:)","abstract":[{"type":"text","text":"Start the PerimeterX SDK."}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:enabledoctorcheck:completion:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:enableDoctorCheck:completion:"}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","kind":"symbol","url":"\/documentation\/perimeterx_sdk","title":"PerimeterX_SDK","type":"topic","abstract":[{"type":"image","identifier":"PerimeterX.png"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"kind":"symbol","abstract":[{"text":"PerimeterX main class.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PerimeterX","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","title":"PerimeterX","navigatorTitle":[{"kind":"identifier","text":"PerimeterX"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/canHandleResponse(forAppId:data:response:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canHandleResponse","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"text":"URLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"This function checks if the SDK can handle the URL request’s response and presents the block screen.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/canHandleResponse(forAppId:data:response:)","navigatorTitle":[{"text":"canHandleResponseForAppId:data:response:","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/canhandleresponse(forappid:data:response:)","role":"symbol","title":"canHandleResponse(forAppId:data:response:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"canHandleResponseForAppId:data:response:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"canHandleResponseForAppId:data:response:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"canHandleResponseForAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"data:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"response:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:enableDoctorCheck:completion:)\/title","value":"startWithAppId:delegate:enableDoctorCheck:completion:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startWithAppId:delegate:enableDoctorCheck:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:enableDoctorCheck:completion:)\/fragments"},{"value":"PerimeterX","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","value":[{"kind":"identifier","text":"PerimeterX"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1canHandleResponse(forAppId:data:response:)\/title","value":"canHandleResponseForAppId:data:response:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1canHandleResponse(forAppId:data:response:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"canHandleResponseForAppId:data:response:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}