{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleResponse","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@PerimeterX_SDK@E@PerimeterXChallengeResult","kind":"typeIdentifier","text":"PerimeterXChallengeResult","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult"},{"kind":"text","text":") -> ())?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"response","content":[{"inlineContent":[{"text":"The response that was received from the URL request.","type":"text"}],"type":"paragraph"}]},{"name":"data","content":[{"inlineContent":[{"text":"The data that was received from the URL request.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The AppID of your account. Ignore this param if you use only one AppID."}],"type":"paragraph"}],"name":"appId"},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback that indicate the challenge’s result. The callback will be called once the user solved (or cancelled)  the challenge. You may use this to retry the URL request."}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the PerimeterX’s payload in the response was handled by the SDK. This function should be used only when the "},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","type":"reference"},{"text":" is set to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","isActive":true},{"text":" in the policy.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"This function handles the URL request’s response and presents the block screen, if necessary."}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/handleResponse(response:data:forAppId:callback:)","interfaceLanguage":"swift"},"metadata":{"title":"handleResponse(response:data:forAppId:callback:)","externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)handleResponseWithResponse:data:forAppId:callback:","modules":[{"name":"PerimeterX_SDK"}],"navigatorTitle":[{"text":"handleResponseWithResponse:data:forAppId:callback:","kind":"identifier"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handleResponse","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"response"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@PerimeterX_SDK@E@PerimeterXChallengeResult","kind":"typeIdentifier","text":"PerimeterXChallengeResult"},{"kind":"text","text":") -> ())?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/handleresponse(response:data:forappid:callback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/handleresponse(response:data:forappid:callback:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PerimeterX","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx","navigatorTitle":[{"kind":"identifier","text":"PerimeterX"}],"title":"PerimeterX","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","abstract":[{"type":"text","text":"PerimeterX main class. You should interact with it in order to setup and start the SDK."}],"role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult":{"navigatorTitle":[{"kind":"identifier","text":"PerimeterXChallengeResult"}],"role":"symbol","title":"PerimeterXChallengeResult","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PerimeterXChallengeResult","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult","abstract":[{"type":"text","text":"Challenge result."}],"type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"title":"PerimeterX_SDK","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","url":"\/documentation\/perimeterx_sdk"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"type":"topic","title":"PXPolicyUrlRequestInterceptionType","role":"symbol","abstract":[{"text":"The URL request interception type.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/none":{"title":"PXPolicyUrlRequestInterceptionType.none","abstract":[{"text":"The SDK does not intercept URL requests at all.","type":"text"}],"kind":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","role":"symbol","type":"topic","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeNone","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/handleResponse(response:data:forAppId:callback:)":{"navigatorTitle":[{"kind":"identifier","text":"handleResponseWithResponse:data:forAppId:callback:"}],"abstract":[{"text":"This function handles the URL request’s response and presents the block screen, if necessary.","type":"text"}],"title":"handleResponse(response:data:forAppId:callback:)","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/handleResponse(response:data:forAppId:callback:)","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/handleresponse(response:data:forappid:callback:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleResponse"},{"kind":"text","text":"("},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@PerimeterX_SDK@E@PerimeterXChallengeResult","text":"PerimeterXChallengeResult","kind":"typeIdentifier"},{"text":") -> ())?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"handleResponseWithResponse:data:forAppId:callback:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"handleResponseWithResponse:data:forAppId:callback:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"handleResponseWithResponse:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSURLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":" "},{"kind":"identifier","text":"data:"},{"kind":"text","text":"("},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"text":" ","kind":"text"},{"text":"forAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"appId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callback:"},{"kind":"text","text":"("},{"text":"void (^)(enum PerimeterXChallengeResult)","preciseIdentifier":"c:BFv(#$@M@PerimeterX_SDK@E@PerimeterXChallengeResult)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"callback","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PerimeterX","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title"},{"value":[{"kind":"identifier","text":"PerimeterX"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/title","value":"PerimeterXChallengeResult"},{"op":"replace","value":[{"text":"PerimeterXChallengeResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/fragments"},{"value":"PXPolicyUrlRequestInterceptionType","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/title","op":"replace"},{"value":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/fragments","op":"replace"},{"op":"replace","value":"PXPolicyUrlRequestInterceptionTypeNone","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/fragments","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}]},{"value":"handleResponseWithResponse:data:forAppId:callback:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1handleResponse(response:data:forAppId:callback:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1handleResponse(response:data:forAppId:callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"handleResponseWithResponse:data:forAppId:callback:","kind":"identifier"}]}]}]}