{"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"text":" if the error is ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeSolved","isActive":true},{"text":" error.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"isChallengeSolvedError(error:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isChallengeSolvedError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"isChallengeSolvedErrorWithError:","kind":"identifier"}],"roleHeading":"Type Method","role":"symbol","externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)isChallengeSolvedErrorWithError:","symbolKind":"method","modules":[{"name":"PerimeterX_SDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isChallengeSolvedError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error to check"}]}],"name":"error"}]},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This kind error should returned when the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","isActive":true},{"text":" is set to any value rather than ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","type":"reference","isActive":true},{"text":".","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/ischallengesolvederror(error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/ischallengesolvederror(error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"sections":[],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isChallengeSolvedError(error:)","interfaceLanguage":"swift"},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/none":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}],"abstract":[{"text":"The SDK does not intercept URL requests at all.","type":"text"}],"title":"PXPolicyUrlRequestInterceptionType.none","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"title":"PerimeterX","abstract":[{"type":"text","text":"PerimeterX main class. You should interact with it in order to setup and start the SDK."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PerimeterX","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PerimeterX","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType":{"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"title":"PXPolicyUrlRequestInterceptionType","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","abstract":[{"text":"The URL request interception type.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode/challengeSolved":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeSolved","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"challengeSolved","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode\/challengesolved","title":"PerimeterXErrorCode.challengeSolved","abstract":[{"type":"text","text":"Challenge was solved by the user."}],"navigatorTitle":[{"text":"PerimeterXErrorCodeChallengeSolved","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"kind":"symbol","type":"topic","abstract":[],"title":"PerimeterX_SDK","role":"collection","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/isChallengeSolvedError(error:)":{"abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the error is "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode\/challengeSolved"},{"type":"text","text":" error."}],"navigatorTitle":[{"kind":"identifier","text":"isChallengeSolvedErrorWithError:"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/ischallengesolvederror(error:)","title":"isChallengeSolvedError(error:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isChallengeSolvedError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/isChallengeSolvedError(error:)","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"isChallengeSolvedErrorWithError:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"isChallengeSolvedErrorWithError:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isChallengeSolvedErrorWithError:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","value":"PXPolicyUrlRequestInterceptionTypeNone","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/title"},{"value":[{"text":"PXPolicyUrlRequestInterceptionTypeNone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","value":"PerimeterX","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","value":[{"kind":"identifier","text":"PerimeterX"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/title","value":"PXPolicyUrlRequestInterceptionType","op":"replace"},{"value":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/fragments"},{"op":"replace","value":"PerimeterXErrorCodeChallengeSolved","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeSolved\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXErrorCode~1challengeSolved\/fragments","value":[{"text":"PerimeterXErrorCodeChallengeSolved","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"isChallengeSolvedErrorWithError:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1isChallengeSolvedError(error:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1isChallengeSolvedError(error:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"isChallengeSolvedErrorWithError:","kind":"identifier"}]}]}]}