{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Register a callback that will be called after the user cancelled the challenge."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerCallbackForChallengeCancelledEvent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> ()) -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AppID of your account. Ignore this param if you use only one AppID."}]}],"name":"appId"},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"text":"The callback to register.","type":"text"}]}]}]},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns the registration ID. Use it to unregister with "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)"},{"text":" function.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This function returns nil on failure."},{"type":"text","text":" "},{"text":"You must call the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)"},{"type":"text","text":" function before calling this function."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/registercallbackforchallengecancelledevent(forappid:callback:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/registercallbackforchallengecancelledevent(forappid:callback:)"]}],"metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerCallbackForChallengeCancelledEvent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": () -> ()) -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)registerCallbackForChallengeCancelledEventForAppId:callback:","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"PerimeterX_SDK"}],"title":"registerCallbackForChallengeCancelledEvent(forAppId:callback:)","navigatorTitle":[{"text":"registerCallbackForChallengeCancelledEventForAppId:callback:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerCallbackForChallengeCancelledEvent(forAppId:callback:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/registerCallbackForChallengeCancelledEvent(forAppId:callback:)":{"title":"registerCallbackForChallengeCancelledEvent(forAppId:callback:)","abstract":[{"type":"text","text":"Register a callback that will be called after the user cancelled the challenge."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerCallbackForChallengeCancelledEvent(forAppId:callback:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerCallbackForChallengeCancelledEvent"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"callback","kind":"externalParam"},{"text":": () -> ()) -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/registercallbackforchallengecancelledevent(forappid:callback:)","kind":"symbol","navigatorTitle":[{"text":"registerCallbackForChallengeCancelledEventForAppId:callback:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"kind":"symbol","abstract":[{"text":"PerimeterX main class.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PerimeterX","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","title":"PerimeterX","navigatorTitle":[{"kind":"identifier","text":"PerimeterX"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterCallbackForChallengeCancelledEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"registrationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"unregisterCallbackForChallengeCancelledEventForAppId:registrationId:"}],"abstract":[{"type":"text","text":"Unregister the callback for challenge cancelled that is associated with the given registration ID."}],"type":"topic","kind":"symbol","title":"unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)","role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/unregistercallbackforchallengecancelledevent(forappid:registrationid:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","kind":"symbol","url":"\/documentation\/perimeterx_sdk","title":"PerimeterX_SDK","type":"topic","abstract":[{"type":"image","identifier":"PerimeterX.png"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:enableDoctorCheck:completion:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate","text":"PerimeterXDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"enableDoctorCheck"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())"}],"title":"start(appId:delegate:enableDoctorCheck:completion:)","abstract":[{"type":"text","text":"Start the PerimeterX SDK."}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:enabledoctorcheck:completion:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:enableDoctorCheck:completion:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"registerCallbackForChallengeCancelledEventForAppId:callback:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"registerCallbackForChallengeCancelledEventForAppId:callback:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"registerCallbackForChallengeCancelledEventForAppId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"appId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"callback:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(void)","kind":"typeIdentifier","preciseIdentifier":"c:BFv()"},{"kind":"text","text":") "},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"registerCallbackForChallengeCancelledEventForAppId:callback:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1registerCallbackForChallengeCancelledEvent(forAppId:callback:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1registerCallbackForChallengeCancelledEvent(forAppId:callback:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"registerCallbackForChallengeCancelledEventForAppId:callback:","kind":"identifier"}]},{"value":"PerimeterX","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","value":[{"kind":"identifier","text":"PerimeterX"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)\/title","value":"unregisterCallbackForChallengeCancelledEventForAppId:registrationId:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"unregisterCallbackForChallengeCancelledEventForAppId:registrationId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:enableDoctorCheck:completion:)\/title","op":"replace","value":"startWithAppId:delegate:enableDoctorCheck:completion:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:enableDoctorCheck:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"startWithAppId:delegate:enableDoctorCheck:completion:","kind":"identifier"}]}]}]}