{"abstract":[{"text":"Provide outgoing URL request to the Account Defender feature.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/registeroutgoingurlrequest(url:forappid:)"]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/registeroutgoingurlrequest(url:forappid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerOutgoingUrlRequest(url:forAppId:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOutgoingUrlRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil) ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL."}]}],"name":"url"},{"content":[{"inlineContent":[{"type":"text","text":"The AppID of your account. Ignore this param if you use only one AppID."}],"type":"paragraph"}],"name":"appId"}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"You must call the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setUserId(userId:forAppId:)","isActive":true,"type":"reference"},{"type":"text","text":" function before calling this function. If the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType"},{"text":" is set to any value rather than ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none"},{"text":", you should not need to use this function (it will be called automatically by the SDK).","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"metadata":{"externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)registerOutgoingUrlRequestWithUrl:forAppId:error:","title":"registerOutgoingUrlRequest(url:forAppId:)","role":"symbol","symbolKind":"method","modules":[{"name":"PerimeterX_SDK"}],"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerOutgoingUrlRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"registerOutgoingUrlRequestWithUrl:forAppId:error:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"navigatorTitle":[{"kind":"identifier","text":"PerimeterX"}],"type":"topic","title":"PerimeterX","role":"symbol","kind":"symbol","abstract":[{"text":"PerimeterX main class. You should interact with it in order to setup and start the SDK.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","url":"\/documentation\/perimeterx_sdk\/perimeterx","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterX"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType":{"title":"PXPolicyUrlRequestInterceptionType","kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType","abstract":[{"text":"The URL request interception type.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionType","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/none":{"abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"title":"PXPolicyUrlRequestInterceptionType.none","role":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/registerOutgoingUrlRequest(url:forAppId:)":{"title":"registerOutgoingUrlRequest(url:forAppId:)","abstract":[{"type":"text","text":"Provide outgoing URL request to the Account Defender feature."}],"role":"symbol","type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterx\/registeroutgoingurlrequest(url:forappid:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerOutgoingUrlRequest","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerOutgoingUrlRequest(url:forAppId:)","kind":"symbol","navigatorTitle":[{"text":"registerOutgoingUrlRequestWithUrl:forAppId:error:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/setUserId(userId:forAppId:)":{"navigatorTitle":[{"text":"setUserIdWithUserId:forAppId:error:","kind":"identifier"}],"abstract":[{"text":"Calling this method with non-","type":"text"},{"code":"null","type":"codeVoice"},{"type":"text","text":" "},{"code":"userId","type":"codeVoice"},{"text":" will start the Account Defender feature.","type":"text"}],"type":"topic","title":"setUserId(userId:forAppId:)","kind":"symbol","role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/setuserid(userid:forappid:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setUserId"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setUserId(userId:forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"title":"PerimeterX_SDK","kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"role":"collection","url":"\/documentation\/perimeterx_sdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"registerOutgoingUrlRequestWithUrl:forAppId:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"registerOutgoingUrlRequestWithUrl:forAppId:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"registerOutgoingUrlRequestWithUrl:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"url","kind":"internalParam"},{"kind":"text","text":" "},{"text":"forAppId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","op":"replace","value":"PerimeterX"},{"value":[{"text":"PerimeterX","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/title","value":"PXPolicyUrlRequestInterceptionType"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType\/fragments","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionType"}]},{"value":"PXPolicyUrlRequestInterceptionTypeNone","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/title"},{"value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeNone"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1registerOutgoingUrlRequest(url:forAppId:)\/title","value":"registerOutgoingUrlRequestWithUrl:forAppId:error:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerOutgoingUrlRequestWithUrl:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1registerOutgoingUrlRequest(url:forAppId:)\/fragments","op":"replace"},{"value":"setUserIdWithUserId:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setUserId(userId:forAppId:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setUserIdWithUserId:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setUserId(userId:forAppId:)\/fragments","op":"replace"}]}]}