{"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setAdditionalData(parameters:forAppId:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Type Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAdditionalData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parameters"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}],"title":"setAdditionalData(parameters:forAppId:)","modules":[{"name":"PerimeterX_SDK"}],"externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)setAdditionalDataWithParameters:forAppId:error:"},"sections":[],"abstract":[{"text":"Set additional data that support Account Defender for given AppID.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setAdditionalData","kind":"identifier"},{"kind":"text","text":"("},{"text":"parameters","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"forAppId"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]},{"parameters":[{"name":"parameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom parameters."}]}]},{"name":"appId","content":[{"inlineContent":[{"type":"text","text":"The AppID to associate the custom parameters with. Ignore this param if you use only one AppID."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"You must call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","type":"reference","isActive":true},{"text":" function before calling this function.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/setadditionaldata(parameters:forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/setadditionaldata(parameters:forappid:)"]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"role":"collection","title":"PerimeterX_SDK","kind":"symbol","url":"\/documentation\/perimeterx_sdk","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/setAdditionalData(parameters:forAppId:)":{"navigatorTitle":[{"text":"setAdditionalDataWithParameters:forAppId:error:","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/setadditionaldata(parameters:forappid:)","abstract":[{"type":"text","text":"Set additional data that support Account Defender for given AppID."}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setAdditionalData(parameters:forAppId:)","kind":"symbol","title":"setAdditionalData(parameters:forAppId:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setAdditionalData","kind":"identifier"},{"kind":"text","text":"("},{"text":"parameters","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"url":"\/documentation\/perimeterx_sdk\/perimeterx","kind":"symbol","navigatorTitle":[{"text":"PerimeterX","kind":"identifier"}],"title":"PerimeterX","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","role":"symbol","abstract":[{"type":"text","text":"PerimeterX main class. You should interact with it in order to setup and start the SDK."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PerimeterX","kind":"identifier"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:policy:)":{"navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"PerimeterXDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"policy"},{"text":": ","kind":"text"},{"text":"PXPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","abstract":[{"type":"text","text":"Start the SDK."}],"title":"start(appId:delegate:policy:)","url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:policy:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"setAdditionalDataWithParameters:forAppId:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"setAdditionalDataWithParameters:forAppId:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setAdditionalDataWithParameters:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>"},{"text":" *) ","kind":"text"},{"text":"parameters","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setAdditionalData(parameters:forAppId:)\/title","op":"replace","value":"setAdditionalDataWithParameters:forAppId:error:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setAdditionalDataWithParameters:forAppId:error:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setAdditionalData(parameters:forAppId:)\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","value":"PerimeterX","op":"replace"},{"op":"replace","value":[{"text":"PerimeterX","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/title","value":"startWithAppId:delegate:policy:error:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"startWithAppId:delegate:policy:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/fragments"}]}]}