{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCustomParameters","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parameters"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"forAppId"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil) ","kind":"text"},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Custom parameters. Each key must be in the following format: “custom_param[x]” where [x] is a number between 1-10."}],"type":"paragraph"}],"name":"parameters"},{"content":[{"inlineContent":[{"type":"text","text":"The AppID to associate the custom parameters with. Ignore this param if you use only one AppID."}],"type":"paragraph"}],"name":"appId"}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"You must call the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","type":"reference","isActive":true},{"type":"text","text":" function before calling this function, otherwise it will throw an error."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"metadata":{"modules":[{"name":"PerimeterX_SDK"}],"title":"setCustomParameters(parameters:forAppId:)","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"setCustomParametersWithParameters:forAppId:error:","kind":"identifier"}],"externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)setCustomParametersWithParameters:forAppId:error:","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCustomParameters","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/setcustomparameters(parameters:forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/setcustomparameters(parameters:forappid:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setCustomParameters(parameters:forAppId:)"},"abstract":[{"type":"text","text":"Set custom parameters for given AppID."}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/setCustomParameters(parameters:forAppId:)":{"kind":"symbol","title":"setCustomParameters(parameters:forAppId:)","abstract":[{"type":"text","text":"Set custom parameters for given AppID."}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/setcustomparameters(parameters:forappid:)","navigatorTitle":[{"text":"setCustomParametersWithParameters:forAppId:error:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCustomParameters"},{"kind":"text","text":"("},{"text":"parameters","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setCustomParameters(parameters:forAppId:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"type":"topic","url":"\/documentation\/perimeterx_sdk","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"title":"PerimeterX_SDK","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:policy:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:policy:)","type":"topic","abstract":[{"type":"text","text":"Start the SDK."}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:policy:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PerimeterXDelegate","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","text":"PXPolicy"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}],"role":"symbol","kind":"symbol","title":"start(appId:delegate:policy:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PerimeterX","kind":"identifier"}],"navigatorTitle":[{"text":"PerimeterX","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","title":"PerimeterX","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx","abstract":[{"type":"text","text":"PerimeterX main class. You should interact with it in order to setup and start the SDK."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"setCustomParametersWithParameters:forAppId:error:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setCustomParametersWithParameters:forAppId:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"setCustomParametersWithParameters:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"parameters","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"setCustomParametersWithParameters:forAppId:error:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setCustomParameters(parameters:forAppId:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setCustomParameters(parameters:forAppId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setCustomParametersWithParameters:forAppId:error:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/title","value":"startWithAppId:delegate:policy:error:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:policy:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startWithAppId:delegate:policy:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","value":"PerimeterX"},{"value":[{"text":"PerimeterX","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments"}]}]}