{"kind":"symbol","metadata":{"externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)setCustomParametersWithParameters:forAppId:completion:","navigatorTitle":[{"text":"setCustomParametersWithParameters:forAppId:completion:","kind":"identifier"}],"modules":[{"name":"PerimeterX_SDK"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCustomParameters","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parameters"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}],"title":"setCustomParameters(parameters:forAppId:completion:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setCustomParameters(parameters:forAppId:completion:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/setcustomparameters(parameters:forappid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/setcustomparameters(parameters:forappid:completion:)"]}],"abstract":[{"type":"text","text":"Set custom parameters for given AppID."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCustomParameters","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"completion","kind":"externalParam"},{"text":": (() -> ())?)","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Custom parameters. Each key must be in the following format: “custom_param[x]” where [x] is a number between 1-10.","type":"text"}]}],"name":"parameters"},{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AppID to associate the custom parameters with. Ignore this param if you use only one AppID."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A completion block. Called after custom parameters were set."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"You must call the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)"},{"type":"text","text":" function before calling this function."}]}]}],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:enableDoctorCheck:completion:)":{"kind":"symbol","abstract":[{"text":"Start the PerimeterX SDK.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:enabledoctorcheck:completion:)","title":"start(appId:delegate:enableDoctorCheck:completion:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:enableDoctorCheck:completion:"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate","kind":"typeIdentifier","text":"PerimeterXDelegate"},{"kind":"text","text":"?, "},{"text":"enableDoctorCheck","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerimeterX"}],"navigatorTitle":[{"text":"PerimeterX","kind":"identifier"}],"abstract":[{"type":"text","text":"PerimeterX main class."}],"role":"symbol","type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterx","kind":"symbol","title":"PerimeterX"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"abstract":[{"type":"image","identifier":"PerimeterX.png"}],"url":"\/documentation\/perimeterx_sdk","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","title":"PerimeterX_SDK","role":"collection","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/setCustomParameters(parameters:forAppId:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"setCustomParametersWithParameters:forAppId:completion:"}],"abstract":[{"type":"text","text":"Set custom parameters for given AppID."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setCustomParameters","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (() -> ())?)"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/setcustomparameters(parameters:forappid:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setCustomParameters(parameters:forAppId:completion:)","title":"setCustomParameters(parameters:forAppId:completion:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"setCustomParametersWithParameters:forAppId:completion:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"setCustomParametersWithParameters:forAppId:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCustomParametersWithParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"text":" *) ","kind":"text"},{"text":"parameters","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"forAppId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:enableDoctorCheck:completion:)\/title","value":"startWithAppId:delegate:enableDoctorCheck:completion:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"startWithAppId:delegate:enableDoctorCheck:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:enableDoctorCheck:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","value":"PerimeterX"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","op":"replace","value":[{"text":"PerimeterX","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setCustomParameters(parameters:forAppId:completion:)\/title","value":"setCustomParametersWithParameters:forAppId:completion:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setCustomParametersWithParameters:forAppId:completion:"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setCustomParameters(parameters:forAppId:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}