{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Set policy for given AppID."}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setPolicy(policy:forAppId:completion:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setPolicyWithPolicy:forAppId:completion:"}],"modules":[{"name":"PerimeterX_SDK"}],"symbolKind":"method","roleHeading":"Type Method","title":"setPolicy(policy:forAppId:completion:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPolicy","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"text":"PXPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}],"externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)setPolicyWithPolicy:forAppId:completion:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/setpolicy(policy:forappid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/setpolicy(policy:forappid:completion:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPolicy"},{"kind":"text","text":"("},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","text":"PXPolicy","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy"},{"text":", ","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":" "},{"text":"appId","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (() -> ())?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"policy","content":[{"type":"paragraph","inlineContent":[{"text":"The policy.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The AppID to associate the policy with. Ignore this param if you use only one AppID.","type":"text"}]}],"name":"appId"},{"content":[{"inlineContent":[{"type":"text","text":"A completion block. Called after the new policy was set."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"You must call the ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)","isActive":true,"type":"reference"},{"type":"text","text":" function before calling this function."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"kind":"symbol","abstract":[{"text":"PerimeterX main class.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PerimeterX","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","title":"PerimeterX","navigatorTitle":[{"kind":"identifier","text":"PerimeterX"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/setPolicy(policy:forAppId:completion:)":{"title":"setPolicy(policy:forAppId:completion:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/setPolicy(policy:forAppId:completion:)","abstract":[{"type":"text","text":"Set policy for given AppID."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPolicy"},{"text":"(","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","text":"PXPolicy"},{"kind":"text","text":", "},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (() -> ())?)"}],"kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/setpolicy(policy:forappid:completion:)","navigatorTitle":[{"kind":"identifier","text":"setPolicyWithPolicy:forAppId:completion:"}],"type":"topic","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The policy that defines the behaviour of the SDK."}],"type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicy","navigatorTitle":[{"text":"PXPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","title":"PXPolicy","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PXPolicy"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","kind":"symbol","url":"\/documentation\/perimeterx_sdk","title":"PerimeterX_SDK","type":"topic","abstract":[{"type":"image","identifier":"PerimeterX.png"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appId:delegate:enableDoctorCheck:completion:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate","text":"PerimeterXDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"enableDoctorCheck"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())"}],"title":"start(appId:delegate:enableDoctorCheck:completion:)","abstract":[{"type":"text","text":"Start the PerimeterX SDK."}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appid:delegate:enabledoctorcheck:completion:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appId:delegate:enableDoctorCheck:completion:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppId:delegate:enableDoctorCheck:completion:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"setPolicyWithPolicy:forAppId:completion:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setPolicyWithPolicy:forAppId:completion:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setPolicyWithPolicy:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","text":"PXPolicy","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"policy"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forAppId:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv()","kind":"typeIdentifier","text":"void (^)(void)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"PerimeterX","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title"},{"value":[{"kind":"identifier","text":"PerimeterX"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","op":"replace"},{"op":"replace","value":"setPolicyWithPolicy:forAppId:completion:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setPolicy(policy:forAppId:completion:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1setPolicy(policy:forAppId:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setPolicyWithPolicy:forAppId:completion:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","value":"PXPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","value":[{"text":"PXPolicy","kind":"identifier"}]},{"value":"startWithAppId:delegate:enableDoctorCheck:completion:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:enableDoctorCheck:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appId:delegate:enableDoctorCheck:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"startWithAppId:delegate:enableDoctorCheck:completion:","kind":"identifier"}]}]}]}