{"abstract":[{"type":"text","text":"Start the SDK."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}],"externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)startWithAppIds:delegate:policy:error:","modules":[{"name":"PerimeterX_SDK"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PerimeterXDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy","kind":"typeIdentifier","text":"PXPolicy"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"start(appIds:delegate:policy:)","symbolKind":"method","role":"symbol"},"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/start(appids:delegate:policy:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/start(appids:delegate:policy:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appIds","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate","kind":"typeIdentifier","text":"PerimeterXDelegate","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","text":"PXPolicy","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}]},{"parameters":[{"name":"appIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The list of AppIDs for your account."}]}]},{"name":"delegate","content":[{"inlineContent":[{"type":"text","text":"A delegate object that conform to "},{"isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate","type":"reference"},{"type":"text","text":" protocol."}],"type":"paragraph"}]},{"name":"policy","content":[{"inlineContent":[{"type":"text","text":"The policy object that config the SDK."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this function to start th SDK with multiple AppIDs. You should call this function only once. You should call this function only from the main thread. This function may throw an error."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"title":"PXPolicy","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PXPolicy"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PXPolicy"}],"abstract":[{"type":"text","text":"The policy that define the behaviour of the SDK."}],"kind":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicy","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"url":"\/documentation\/perimeterx_sdk","abstract":[],"title":"PerimeterX_SDK","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","kind":"symbol","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate":{"abstract":[{"type":"text","text":"PerimeterX protocol"}],"role":"symbol","kind":"symbol","title":"PerimeterXDelegate","navigatorTitle":[{"kind":"identifier","text":"PerimeterXDelegate"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PerimeterXDelegate","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerimeterX"}],"navigatorTitle":[{"text":"PerimeterX","kind":"identifier"}],"title":"PerimeterX","abstract":[{"type":"text","text":"PerimeterX main class. You should interact with it in order to setup and start the SDK."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/start(appIds:delegate:policy:)":{"url":"\/documentation\/perimeterx_sdk\/perimeterx\/start(appids:delegate:policy:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/start(appIds:delegate:policy:)","navigatorTitle":[{"kind":"identifier","text":"startWithAppIds:delegate:policy:error:"}],"kind":"symbol","abstract":[{"text":"Start the SDK.","type":"text"}],"title":"start(appIds:delegate:policy:)","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appIds"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate","text":"PerimeterXDelegate"},{"kind":"text","text":"?, "},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PXPolicy","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"startWithAppIds:delegate:policy:error:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"startWithAppIds:delegate:policy:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"startWithAppIds:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"appIds","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate","kind":"typeIdentifier","text":"id<PerimeterXDelegate>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"text":"policy:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","text":"PXPolicy","preciseIdentifier":"c:@M@PerimeterX_SDK@objc(cs)PXPolicy"},{"kind":"text","text":" *) "},{"text":"policy","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title","value":"PXPolicy","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","value":[{"text":"PXPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/title","value":"PerimeterXDelegate"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/fragments","value":[{"kind":"identifier","text":"PerimeterXDelegate"}],"op":"replace"},{"value":"PerimeterX","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","value":[{"kind":"identifier","text":"PerimeterX"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appIds:delegate:policy:)\/title","value":"startWithAppIds:delegate:policy:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1start(appIds:delegate:policy:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppIds:delegate:policy:error:"}]}]}]}