{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"modules":[{"name":"PerimeterX_SDK"}],"symbolKind":"method","externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)unregisterCallbackForChallengeCancelledEventForAppId:registrationId:","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterCallbackForChallengeCancelledEvent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"registrationId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"unregisterCallbackForChallengeCancelledEventForAppId:registrationId:","kind":"identifier"}],"title":"unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"abstract":[{"text":"Unregister the callback for challenge cancelled that is associated with the given registration ID.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unregisterCallbackForChallengeCancelledEvent","kind":"identifier"},{"kind":"text","text":"("},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":" "},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"registrationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"text":"The AppID of your account. Ignore this param if you use only one AppID.","type":"text"}]}]},{"name":"registrationId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The registration ID."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Registration ID is provided from the "},{"type":"codeVoice","code":"registerCallbackForRequestCancelledEvent(forAppId:callback:)"},{"type":"text","text":" function."}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/unregistercallbackforchallengecancelledevent(forappid:registrationid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/unregistercallbackforchallengecancelledevent(forappid:registrationid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerimeterX"}],"navigatorTitle":[{"text":"PerimeterX","kind":"identifier"}],"abstract":[{"type":"text","text":"PerimeterX main class."}],"role":"symbol","type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterx","kind":"symbol","title":"PerimeterX"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"abstract":[{"type":"image","identifier":"PerimeterX.png"}],"url":"\/documentation\/perimeterx_sdk","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","title":"PerimeterX_SDK","role":"collection","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)","navigatorTitle":[{"text":"unregisterCallbackForChallengeCancelledEventForAppId:registrationId:","kind":"identifier"}],"abstract":[{"type":"text","text":"Unregister the callback for challenge cancelled that is associated with the given registration ID."}],"type":"topic","title":"unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterCallbackForChallengeCancelledEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"registrationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterx\/unregistercallbackforchallengecancelledevent(forappid:registrationid:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"unregisterCallbackForChallengeCancelledEventForAppId:registrationId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unregisterCallbackForChallengeCancelledEventForAppId:registrationId:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"unregisterCallbackForChallengeCancelledEventForAppId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registrationId:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"registrationId"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"PerimeterX","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","value":[{"text":"PerimeterX","kind":"identifier"}]},{"value":"unregisterCallbackForChallengeCancelledEventForAppId:registrationId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"unregisterCallbackForChallengeCancelledEventForAppId:registrationId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1unregisterCallbackForChallengeCancelledEvent(forAppId:registrationId:)\/fragments"}]}]}