{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterCallbackForRequestBlockedEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"registrationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AppID of your account. Ignore this param if you use only one AppID."}]}]},{"name":"registrationId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The registration ID."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Registration ID is provided from the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerCallbackForRequestBlockedEvent(forAppId:callback:)"},{"type":"text","text":" function."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/unregistercallbackforrequestblockedevent(forappid:registrationid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/unregistercallbackforrequestblockedevent(forappid:registrationid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/unregisterCallbackForRequestBlockedEvent(forAppId:registrationId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Unregister the callback for request blocked that is associated with the given registration ID."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterCallbackForRequestBlockedEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"registrationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"unregisterCallbackForRequestBlockedEvent(forAppId:registrationId:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)unregisterCallbackForRequestBlockedEventForAppId:registrationId:","modules":[{"name":"PerimeterX_SDK"}],"navigatorTitle":[{"kind":"identifier","text":"unregisterCallbackForRequestBlockedEventForAppId:registrationId:"}]},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/registerCallbackForRequestBlockedEvent(forAppId:callback:)":{"role":"symbol","title":"registerCallbackForRequestBlockedEvent(forAppId:callback:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerCallbackForRequestBlockedEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": () -> ()) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Register a callback that will be called after a request was blocked."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerCallbackForRequestBlockedEvent(forAppId:callback:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerCallbackForRequestBlockedEventForAppId:callback:"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/registercallbackforrequestblockedevent(forappid:callback:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/unregisterCallbackForRequestBlockedEvent(forAppId:registrationId:)":{"role":"symbol","title":"unregisterCallbackForRequestBlockedEvent(forAppId:registrationId:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterCallbackForRequestBlockedEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"registrationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unregister the callback for request blocked that is associated with the given registration ID."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/unregisterCallbackForRequestBlockedEvent(forAppId:registrationId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unregisterCallbackForRequestBlockedEventForAppId:registrationId:"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/unregistercallbackforrequestblockedevent(forappid:registrationid:)"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"role":"symbol","title":"PerimeterX","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterX"}],"abstract":[{"type":"text","text":"PerimeterX main class."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PerimeterX"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"role":"collection","title":"PerimeterX_SDK","abstract":[{"type":"image","identifier":"PerimeterX.png"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","kind":"symbol","type":"topic","url":"\/documentation\/perimeterx_sdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"unregisterCallbackForRequestBlockedEventForAppId:registrationId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unregisterCallbackForRequestBlockedEventForAppId:registrationId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"unregisterCallbackForRequestBlockedEventForAppId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"kind":"text","text":" "},{"kind":"identifier","text":"registrationId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"registrationId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1registerCallbackForRequestBlockedEvent(forAppId:callback:)\/title","value":"registerCallbackForRequestBlockedEventForAppId:callback:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1registerCallbackForRequestBlockedEvent(forAppId:callback:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerCallbackForRequestBlockedEventForAppId:callback:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1unregisterCallbackForRequestBlockedEvent(forAppId:registrationId:)\/title","value":"unregisterCallbackForRequestBlockedEventForAppId:registrationId:"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1unregisterCallbackForRequestBlockedEvent(forAppId:registrationId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unregisterCallbackForRequestBlockedEventForAppId:registrationId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","value":"PerimeterX"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","value":[{"kind":"identifier","text":"PerimeterX"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}