{"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/unregistercallbackforchallengesolvedevent(forappid:registrationid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterx\/unregistercallbackforchallengesolvedevent(forappid:registrationid:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/unregisterCallbackForChallengeSolvedEvent(forAppId:registrationId:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Unregister the callback for challenge solved that is associated with the given registration ID."}],"metadata":{"title":"unregisterCallbackForChallengeSolvedEvent(forAppId:registrationId:)","externalID":"c:@M@PerimeterX_SDK@objc(cs)PerimeterX(cm)unregisterCallbackForChallengeSolvedEventForAppId:registrationId:","navigatorTitle":[{"kind":"identifier","text":"unregisterCallbackForChallengeSolvedEventForAppId:registrationId:"}],"modules":[{"name":"PerimeterX_SDK"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterCallbackForChallengeSolvedEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"registrationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterCallbackForChallengeSolvedEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"registrationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AppID of your account. Ignore this param if you use only one AppID."}]}],"name":"appId"},{"name":"registrationId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The registration ID."}]}]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Registration ID is provided from the "},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerCallbackForChallengeSolvedEvent(forAppId:callback:)","isActive":true,"type":"reference"},{"type":"text","text":" function."}]}],"kind":"content"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"kind":"symbol","abstract":[{"text":"PerimeterX main class.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PerimeterX","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","title":"PerimeterX","navigatorTitle":[{"kind":"identifier","text":"PerimeterX"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","kind":"symbol","url":"\/documentation\/perimeterx_sdk","title":"PerimeterX_SDK","type":"topic","abstract":[{"type":"image","identifier":"PerimeterX.png"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/unregisterCallbackForChallengeSolvedEvent(forAppId:registrationId:)":{"title":"unregisterCallbackForChallengeSolvedEvent(forAppId:registrationId:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/unregisterCallbackForChallengeSolvedEvent(forAppId:registrationId:)","abstract":[{"type":"text","text":"Unregister the callback for challenge solved that is associated with the given registration ID."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterCallbackForChallengeSolvedEvent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"registrationId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/unregistercallbackforchallengesolvedevent(forappid:registrationid:)","role":"symbol","navigatorTitle":[{"text":"unregisterCallbackForChallengeSolvedEventForAppId:registrationId:","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/registerCallbackForChallengeSolvedEvent(forAppId:callback:)":{"title":"registerCallbackForChallengeSolvedEvent(forAppId:callback:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/registerCallbackForChallengeSolvedEvent(forAppId:callback:)","abstract":[{"text":"Register a callback that will be called after the user solved the challenge.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerCallbackForChallengeSolvedEvent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": () -> ()) -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/registercallbackforchallengesolvedevent(forappid:callback:)","role":"symbol","navigatorTitle":[{"text":"registerCallbackForChallengeSolvedEventForAppId:callback:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"unregisterCallbackForChallengeSolvedEventForAppId:registrationId:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unregisterCallbackForChallengeSolvedEventForAppId:registrationId:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"unregisterCallbackForChallengeSolvedEventForAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"appId"},{"text":" ","kind":"text"},{"text":"registrationId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"registrationId"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title","value":"PerimeterX","op":"replace"},{"value":[{"kind":"identifier","text":"PerimeterX"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments"},{"value":"unregisterCallbackForChallengeSolvedEventForAppId:registrationId:","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1unregisterCallbackForChallengeSolvedEvent(forAppId:registrationId:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1unregisterCallbackForChallengeSolvedEvent(forAppId:registrationId:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unregisterCallbackForChallengeSolvedEventForAppId:registrationId:"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1registerCallbackForChallengeSolvedEvent(forAppId:callback:)\/title","op":"replace","value":"registerCallbackForChallengeSolvedEventForAppId:callback:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerCallbackForChallengeSolvedEventForAppId:callback:"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1registerCallbackForChallengeSolvedEvent(forAppId:callback:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}