{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk"]},{"paths":["\/documentation\/perimeterx_sdk"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"PerimeterX is the leading provider of application security solutions that keep your business safe in the digital world. Delivered as a service, the company’s Bot Defender, Code Defender and Page Defender solutions detect risks to your web applications and proactively manage them, freeing you to focus on growth and innovation. The world’s largest and most reputable websites and mobile applications count on PerimeterX to safeguard their consumers’ digital experience. PerimeterX is headquartered in San Mateo, California and at "},{"type":"reference","identifier":"https:\/\/perimeterx.com","isActive":true},{"text":".","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"image","identifier":"PerimeterX.png"}],"metadata":{"externalID":"PerimeterX_SDK","symbolKind":"module","role":"collection","modules":[{"name":"PerimeterX_SDK"}],"title":"PerimeterX_SDK","roleHeading":"Framework"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[[]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/BeyondTheBasic","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/IntegrationGuide","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/Migration"],"generated":true,"title":"Articles"},{"title":"Classes","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]},{"title":"Protocols","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate"]},{"title":"Variables","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorDomain"]},{"title":"Enumerations","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyChallengeType":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PXPolicyChallengeType","kind":"identifier"}],"url":"\/documentation\/perimeterx_sdk\/pxpolicychallengetype","title":"PXPolicyChallengeType","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Challenge type."}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType","navigatorTitle":[{"text":"PXPolicyChallengeType","kind":"identifier"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/Migration":{"abstract":[{"type":"text","text":"In this article we will explore how to upgrade the Perimeter X iOS SDK from an earlier version (1.x and below) to version 2.0."}],"type":"topic","kind":"article","title":"Migration from earlier SDK versions","url":"\/documentation\/perimeterx_sdk\/migration","role":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/Migration"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorCode":{"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerimeterXErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode","abstract":[{"type":"text","text":"PerimeterX error codes. This will be included in errors objects that generated in the SDK."}],"title":"PerimeterXErrorCode","navigatorTitle":[{"text":"PerimeterXErrorCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxerrorcode"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXErrorDomain":{"url":"\/documentation\/perimeterx_sdk\/perimeterxerrordomain","title":"PerimeterXErrorDomain","abstract":[{"type":"text","text":"PerimeterX error domain. This will be included in errors objects that generated in the SDK. List of error codes is defined in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorCode"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXErrorDomain","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterXErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate":{"navigatorTitle":[{"text":"PerimeterXDelegate","kind":"identifier"}],"abstract":[{"text":"PerimeterX protocol","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerimeterXDelegate"}],"type":"topic","title":"PerimeterXDelegate","url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate","role":"symbol","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXVersionNumber":{"role":"symbol","fragments":[{"text":"PerimeterXVersionNumber","kind":"identifier"}],"type":"topic","kind":"symbol","title":"PerimeterXVersionNumber","url":"\/documentation\/perimeterx_sdk\/perimeterxversionnumber","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXVersionNumber","abstract":[{"type":"text","text":"Project version number for PerimeterX."}]},"https://perimeterx.com":{"url":"https:\/\/perimeterx.com","identifier":"https:\/\/perimeterx.com","type":"link","titleInlineContent":[{"type":"text","text":"perimeterx.com"}],"title":"perimeterx.com"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"abstract":[{"type":"image","identifier":"PerimeterX.png"}],"url":"\/documentation\/perimeterx_sdk","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","title":"PerimeterX_SDK","role":"collection","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PerimeterX"}],"navigatorTitle":[{"text":"PerimeterX","kind":"identifier"}],"abstract":[{"type":"text","text":"PerimeterX main class."}],"role":"symbol","type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterx","kind":"symbol","title":"PerimeterX"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/IntegrationGuide":{"role":"article","url":"\/documentation\/perimeterx_sdk\/integrationguide","abstract":[{"text":"This document provides instructions to how to integrate Perimeter X iOS SDK v2.0 into your project.","type":"text"}],"type":"topic","title":"Integration Guide","kind":"article","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/IntegrationGuide"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/BeyondTheBasic":{"role":"article","url":"\/documentation\/perimeterx_sdk\/beyondthebasic","abstract":[{"text":"In this article we will explore more advanced topics that will help you to get the most out of the SDK.","type":"text"}],"type":"topic","title":"Beyond the Basic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/BeyondTheBasic","kind":"article"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXVersionString":{"abstract":[{"type":"text","text":"Project version string for PerimeterX."}],"fragments":[{"text":"PerimeterXVersionString","kind":"identifier"}],"type":"topic","kind":"symbol","title":"PerimeterXVersionString","url":"\/documentation\/perimeterx_sdk\/perimeterxversionstring","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXVersionString"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy":{"type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","url":"\/documentation\/perimeterx_sdk\/pxpolicy","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PXPolicy","kind":"identifier"}],"abstract":[{"type":"text","text":"The policy that defines the behaviour of the SDK."}],"title":"PXPolicy","navigatorTitle":[{"kind":"identifier","text":"PXPolicy"}]},"PerimeterX.png":{"identifier":"PerimeterX.png","type":"image","alt":"PerimeterX","variants":[{"traits":["2x","light"],"url":"\/images\/PerimeterX@2x.png"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Articles","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/BeyondTheBasic","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/IntegrationGuide","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/Migration"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX"]},{"identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXVersionNumber","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyChallengeType"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"PXPolicyChallengeType","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyChallengeType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyChallengeType\/fragments","value":[{"text":"PXPolicyChallengeType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/title","op":"replace","value":"PerimeterXDelegate"},{"value":[{"kind":"identifier","text":"PerimeterXDelegate"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/fragments","op":"replace"},{"op":"replace","value":"PerimeterX","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX\/fragments","value":[{"kind":"identifier","text":"PerimeterX"}],"op":"replace"},{"op":"replace","value":"PXPolicy","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/title"},{"value":[{"text":"PXPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy\/fragments","op":"replace"}]}]}