{"metadata":{"symbolKind":"case","modules":[{"name":"PerimeterX_SDK"}],"externalID":"c:@M@PerimeterX_SDK@E@PerimeterXChallengeResult@PerimeterXChallengeResultCancelled","title":"PerimeterXChallengeResult.cancelled","navigatorTitle":[{"kind":"identifier","text":"PerimeterXChallengeResultCancelled"}],"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/cancelled","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/cancelled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/cancelled"]}],"abstract":[{"type":"text","text":"Challenge was cancelled."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cancelled","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult/cancelled":{"title":"PerimeterXChallengeResult.cancelled","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/cancelled","role":"symbol","navigatorTitle":[{"text":"PerimeterXChallengeResultCancelled","kind":"identifier"}],"type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/cancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cancelled","kind":"identifier"}],"abstract":[{"text":"Challenge was cancelled.","type":"text"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"url":"\/documentation\/perimeterx_sdk","abstract":[],"title":"PerimeterX_SDK","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","kind":"symbol","type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult","abstract":[{"text":"Challenge result.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult","title":"PerimeterXChallengeResult","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerimeterXChallengeResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PerimeterXChallengeResult"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"PerimeterXChallengeResultCancelled"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PerimeterXChallengeResultCancelled","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"PerimeterXChallengeResultCancelled","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PerimeterXChallengeResultCancelled","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult~1cancelled\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PerimeterXChallengeResultCancelled"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult~1cancelled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/title","value":"PerimeterXChallengeResult"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/fragments","value":[{"text":"PerimeterXChallengeResult","kind":"identifier"}],"op":"replace"}]}]}