{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/Equatable-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/equatable-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"article","metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"PerimeterX_SDK"}],"role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult"]]},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult":{"type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerimeterXChallengeResult","kind":"identifier"}],"title":"PerimeterXChallengeResult","navigatorTitle":[{"text":"PerimeterXChallengeResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Challenge result."}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"url":"\/documentation\/perimeterx_sdk","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"role":"collection","kind":"symbol","type":"topic","title":"PerimeterX_SDK"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult/!=(_:_:)":{"title":"!=(_:_:)","abstract":[],"role":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/!=(_:_:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/!=(_:_:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/title","op":"replace","value":"PerimeterXChallengeResult"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/fragments","op":"replace","value":[{"text":"PerimeterXChallengeResult","kind":"identifier"}]},{"op":"replace","value":[{"text":"PerimeterXChallengeResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/navigatorTitle"}]}]}