{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"solved","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult"]]},"metadata":{"modules":[{"name":"PerimeterX_SDK"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"PerimeterXChallengeResultSolved"}],"title":"PerimeterXChallengeResult.solved","externalID":"c:@M@PerimeterX_SDK@E@PerimeterXChallengeResult@PerimeterXChallengeResultSolved","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"solved","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/solved","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Challenge was solved."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/solved"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/solved"]}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"abstract":[],"title":"PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk","type":"topic","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","role":"collection","kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult":{"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerimeterXChallengeResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Challenge result."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PerimeterXChallengeResult"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult","title":"PerimeterXChallengeResult","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXChallengeResult/solved":{"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"solved"}],"abstract":[{"type":"text","text":"Challenge was solved."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PerimeterXChallengeResultSolved"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxchallengeresult\/solved","title":"PerimeterXChallengeResult.solved","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXChallengeResult\/solved"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PerimeterXChallengeResultSolved","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PerimeterXChallengeResultSolved","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PerimeterXChallengeResultSolved","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/title","value":"PerimeterXChallengeResult","op":"replace"},{"value":[{"kind":"identifier","text":"PerimeterXChallengeResult"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult~1solved\/title","value":"PerimeterXChallengeResultSolved"},{"value":[{"text":"PerimeterXChallengeResultSolved","kind":"identifier"}],"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXChallengeResult~1solved\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}