{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidRenderChallenge(forAppId:)"},"metadata":{"role":"symbol","modules":[{"name":"PerimeterX_SDK"}],"externalID":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate(im)perimeterxDidRenderChallengeForAppId:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perimeterxDidRenderChallenge"},{"kind":"text","text":"("},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"perimeterxDidRenderChallenge(forAppId:)","navigatorTitle":[{"kind":"identifier","text":"perimeterxDidRenderChallengeForAppId:"}],"symbolKind":"method","required":true,"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidrenderchallenge(forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidrenderchallenge(forappid:)"]}],"abstract":[{"text":"Called when the challenge was render successfully.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"perimeterxDidRenderChallenge"},{"text":"(","kind":"text"},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AppID that related to the event."}]}],"name":"appId"}],"kind":"parameters"}],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"url":"\/documentation\/perimeterx_sdk","role":"collection","kind":"symbol","type":"topic","title":"PerimeterX_SDK","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate":{"title":"PerimeterXDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerimeterXDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PerimeterXDelegate"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate","type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"PerimeterX protocol"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate/perimeterxDidRenderChallenge(forAppId:)":{"title":"perimeterxDidRenderChallenge(forAppId:)","required":true,"url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidrenderchallenge(forappid:)","kind":"symbol","abstract":[{"text":"Called when the challenge was render successfully.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"perimeterxDidRenderChallenge","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidRenderChallenge(forAppId:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"perimeterxDidRenderChallengeForAppId:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"perimeterxDidRenderChallengeForAppId:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"perimeterxDidRenderChallengeForAppId:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"perimeterxDidRenderChallengeForAppId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PerimeterXDelegate","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/fragments","value":[{"text":"PerimeterXDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidRenderChallenge(forAppId:)\/title","value":"perimeterxDidRenderChallengeForAppId:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidRenderChallenge(forAppId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"perimeterxDidRenderChallengeForAppId:"}],"op":"replace"}]}]}