{"abstract":[{"text":"Called when a request was blocked.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perimeterxDidRequestBlocked"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The AppID that related to the event.","type":"text"}]}],"name":"appId"},{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The request’s URL that was blocked. Will be "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" when "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType"},{"text":" is set to ","type":"text"},{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","type":"reference","isActive":true},{"text":" in the policy.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidrequestblocked(url:appid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidrequestblocked(url:appid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidRequestBlocked(url:appId:)"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate"]]},"metadata":{"role":"symbol","symbolKind":"method","title":"perimeterxDidRequestBlocked(url:appId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perimeterxDidRequestBlocked"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"externalID":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate(im)perimeterxDidRequestBlockedWithUrl:appId:","roleHeading":"Instance Method","modules":[{"name":"PerimeterX_SDK"}],"navigatorTitle":[{"text":"perimeterxDidRequestBlockedWithUrl:appId:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/none":{"url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/none","type":"topic","navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeNone","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"abstract":[{"type":"text","text":"The SDK does not intercept URL requests at all."}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/none","title":"PXPolicyUrlRequestInterceptionType.none"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicyUrlRequestInterceptionType/intercept":{"title":"PXPolicyUrlRequestInterceptionType.intercept","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/pxpolicyurlrequestinterceptiontype\/intercept","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"intercept","kind":"identifier"}],"navigatorTitle":[{"text":"PXPolicyUrlRequestInterceptionTypeIntercept","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"The SDK intercepts URL requests in order to add HTTP headers and handle block responses.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The SDK can intercept those types of requests:"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PXPolicy/urlRequestInterceptionType":{"abstract":[{"type":"text","text":"Decide how the SDK should handle URL requests. Default is "},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicyUrlRequestInterceptionType\/intercept","isActive":true},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/perimeterx_sdk\/pxpolicy\/urlrequestinterceptiontype","role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PXPolicy\/urlRequestInterceptionType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"urlRequestInterceptionType"}],"title":"urlRequestInterceptionType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlRequestInterceptionType"},{"kind":"text","text":": "},{"text":"PXPolicyUrlRequestInterceptionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@PerimeterX_SDK@E@PXPolicyUrlRequestInterceptionType"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate/perimeterxDidRequestBlocked(url:appId:)":{"title":"perimeterxDidRequestBlocked(url:appId:)","navigatorTitle":[{"text":"perimeterxDidRequestBlockedWithUrl:appId:","kind":"identifier"}],"abstract":[{"text":"Called when a request was blocked.","type":"text"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidRequestBlocked(url:appId:)","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidrequestblocked(url:appid:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"perimeterxDidRequestBlocked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","url":"\/documentation\/perimeterx_sdk","title":"PerimeterX_SDK","type":"topic","role":"collection","abstract":[],"kind":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate":{"navigatorTitle":[{"kind":"identifier","text":"PerimeterXDelegate"}],"role":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate","title":"PerimeterXDelegate","kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PerimeterXDelegate","kind":"identifier"}],"type":"topic","abstract":[{"text":"PerimeterX protocol","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"perimeterxDidRequestBlockedWithUrl:appId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"perimeterxDidRequestBlockedWithUrl:appId:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"perimeterxDidRequestBlockedWithUrl:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"appId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/title","value":"PXPolicyUrlRequestInterceptionTypeNone"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1none\/fragments","op":"replace","value":[{"text":"PXPolicyUrlRequestInterceptionTypeNone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/title","value":"PXPolicyUrlRequestInterceptionTypeIntercept","op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicyUrlRequestInterceptionType~1intercept\/fragments","op":"replace","value":[{"kind":"identifier","text":"PXPolicyUrlRequestInterceptionTypeIntercept"}]},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1urlRequestInterceptionType\/title","value":"urlRequestInterceptionType"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PXPolicy~1urlRequestInterceptionType\/fragments","value":[{"text":"urlRequestInterceptionType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidRequestBlocked(url:appId:)\/title","op":"replace","value":"perimeterxDidRequestBlockedWithUrl:appId:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidRequestBlocked(url:appId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"perimeterxDidRequestBlockedWithUrl:appId:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/title","op":"replace","value":"PerimeterXDelegate"},{"value":[{"text":"PerimeterXDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/fragments"}]}]}