{"metadata":{"modules":[{"name":"PerimeterX_SDK"}],"symbolKind":"method","title":"perimeterxDidFailRenderChallenge(forAppId:)","externalID":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate(im)perimeterxDidFailRenderChallengeForAppId:","roleHeading":"Instance Method","required":true,"navigatorTitle":[{"kind":"identifier","text":"perimeterxDidFailRenderChallengeForAppId:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"perimeterxDidFailRenderChallenge","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate"]]},"abstract":[{"text":"Called when the challenge was failed to render.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"perimeterxDidFailRenderChallenge","kind":"identifier"},{"kind":"text","text":"("},{"text":"forAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"text":"The AppID that related to the event.","type":"text"}]}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidFailRenderChallenge(forAppId:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidfailrenderchallenge(forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidfailrenderchallenge(forappid:)"]}],"sections":[],"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate/perimeterxDidFailRenderChallenge(forAppId:)":{"title":"perimeterxDidFailRenderChallenge(forAppId:)","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxDidFailRenderChallenge(forAppId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perimeterxDidFailRenderChallenge"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAppId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"perimeterxDidFailRenderChallengeForAppId:","kind":"identifier"}],"required":true,"kind":"symbol","type":"topic","abstract":[{"text":"Called when the challenge was failed to render.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxdidfailrenderchallenge(forappid:)","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"type":"topic","url":"\/documentation\/perimeterx_sdk","kind":"symbol","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[],"title":"PerimeterX_SDK","role":"collection"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PerimeterXDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate","abstract":[{"type":"text","text":"PerimeterX protocol"}],"title":"PerimeterXDelegate","navigatorTitle":[{"text":"PerimeterXDelegate","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"perimeterxDidFailRenderChallengeForAppId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"perimeterxDidFailRenderChallengeForAppId:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"perimeterxDidFailRenderChallengeForAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"perimeterxDidFailRenderChallengeForAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidFailRenderChallenge(forAppId:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"perimeterxDidFailRenderChallengeForAppId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxDidFailRenderChallenge(forAppId:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/title","value":"PerimeterXDelegate"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"PerimeterXDelegate"}]}]}]}