{"abstract":[{"text":"Called when the HTTP headers were changed. You may store and use those headers instead of calling the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/headersForURLRequest(forAppId:)","isActive":true},{"text":" function for every URL request.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perimeterxHeadersWereUpdated"},{"text":"(","kind":"text"},{"text":"headers","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":" "},{"text":"appId","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"HTTP headers.","type":"text"}]}],"name":"headers"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AppID that related to the event."}]}],"name":"appId"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxheaderswereupdated(headers:forappid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxheaderswereupdated(headers:forappid:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate"]]},"metadata":{"symbolKind":"method","modules":[{"name":"PerimeterX_SDK"}],"role":"symbol","roleHeading":"Instance Method","title":"perimeterxHeadersWereUpdated(headers:forAppId:)","externalID":"c:@M@PerimeterX_SDK@objc(pl)PerimeterXDelegate(im)perimeterxHeadersWereUpdatedWithHeaders:forAppId:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perimeterxHeadersWereUpdated"},{"kind":"text","text":"("},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"forAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"perimeterxHeadersWereUpdatedWithHeaders:forAppId:","kind":"identifier"}],"required":true},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxHeadersWereUpdated(headers:forAppId:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate":{"title":"PerimeterXDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PerimeterXDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PerimeterXDelegate"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate","type":"topic","url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"PerimeterX protocol"}]},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterXDelegate/perimeterxHeadersWereUpdated(headers:forAppId:)":{"abstract":[{"type":"text","text":"Called when the HTTP headers were changed. You may store and use those headers instead of calling the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/headersForURLRequest(forAppId:)"},{"text":" function for every URL request.","type":"text"}],"url":"\/documentation\/perimeterx_sdk\/perimeterxdelegate\/perimeterxheaderswereupdated(headers:forappid:)","type":"topic","role":"symbol","title":"perimeterxHeadersWereUpdated(headers:forAppId:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"perimeterxHeadersWereUpdated","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"headers"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"forAppId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"perimeterxHeadersWereUpdatedWithHeaders:forAppId:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterXDelegate\/perimeterxHeadersWereUpdated(headers:forAppId:)","required":true},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK/PerimeterX/headersForURLRequest(forAppId:)":{"abstract":[{"type":"text","text":"Returns HTTP headers that should be added to the URL request."}],"type":"topic","navigatorTitle":[{"text":"headersForURLRequestForAppId:","kind":"identifier"}],"identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK\/PerimeterX\/headersForURLRequest(forAppId:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"headersForURLRequest","kind":"identifier"},{"kind":"text","text":"("},{"text":"forAppId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"url":"\/documentation\/perimeterx_sdk\/perimeterx\/headersforurlrequest(forappid:)","kind":"symbol","title":"headersForURLRequest(forAppId:)","role":"symbol"},"doc://com.perimeterx.mobile-sdk/documentation/PerimeterX_SDK":{"url":"\/documentation\/perimeterx_sdk","role":"collection","kind":"symbol","type":"topic","title":"PerimeterX_SDK","identifier":"doc:\/\/com.perimeterx.mobile-sdk\/documentation\/PerimeterX_SDK","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"perimeterxHeadersWereUpdatedWithHeaders:forAppId:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"perimeterxHeadersWereUpdatedWithHeaders:forAppId:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"perimeterxHeadersWereUpdatedWithHeaders:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"headers"},{"text":" ","kind":"text"},{"text":"forAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/title","value":"PerimeterXDelegate"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"PerimeterXDelegate"}]},{"value":"perimeterxHeadersWereUpdatedWithHeaders:forAppId:","op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxHeadersWereUpdated(headers:forAppId:)\/title"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterXDelegate~1perimeterxHeadersWereUpdated(headers:forAppId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"perimeterxHeadersWereUpdatedWithHeaders:forAppId:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1headersForURLRequest(forAppId:)\/title","value":"headersForURLRequestForAppId:"},{"path":"\/references\/doc:~1~1com.perimeterx.mobile-sdk~1documentation~1PerimeterX_SDK~1PerimeterX~1headersForURLRequest(forAppId:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"headersForURLRequestForAppId:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}